import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { ArrowRight, BarChart3, Calculator, Check, Compass, FileSearch } from 'lucide-react';
import { chatGPTSignInPath, getChatGPTUser } from '@/app/chatgpt-auth';
import { isLocale, type Locale } from '@/lib/i18n';
import { memberCopy } from '@/lib/member-copy';
import { localizedPageMetadata } from '@/lib/seo';
export async function generateMetadata():Promise<Metadata>{const h=await headers();const raw=h.get('x-nexavoris-locale');const locale:Locale=isLocale(raw)?raw:'en';const t=memberCopy[locale];return localizedPageMetadata(t.free,t.freeIntro,'/free-account',locale)}
export default async function FreeAccountPage(){const h=await headers();const raw=h.get('x-nexavoris-locale');const locale:Locale=isLocale(raw)?raw:'en';const t=memberCopy[locale];const user=await getChatGPTUser();const benefits=[[BarChart3,t.assessment],[Compass,t.opportunity],[Calculator,t.roi],[FileSearch,t.roadmap]] as const;return <main className="free-account-page"><section className="free-account-hero section-shell"><span className="section-index">FREE BUSINESS TOOLS</span><h1>{t.free}</h1><p>{t.freeIntro}</p><div className="actions">{user?<a className="button primary" href="/account">{t.dashboard}<ArrowRight size={16}/></a>:<a className="button primary" href={chatGPTSignInPath('/account')} target="_top">{t.create}<ArrowRight size={16}/></a>}<a className="button secondary" href="/assessment">{t.start}</a></div><small>{t.nocard}</small></section><section className="section-shell account-benefits"><div className="section-head"><span className="section-index">INCLUDED FREE</span><h2>Useful business analysis you can keep and improve.</h2></div><div>{benefits.map(([Icon,label])=><article key={label}><Icon/><h3>{label}</h3><p><Check size={15}/> Personalized results</p><p><Check size={15}/> Saved to your account</p></article>)}</div></section></main>}
