import type { Metadata } from 'next'; import { SolutionPage } from '@/components/solution-page'; import { ScreenshotGallery } from '@/components/screenshot-gallery';
export const metadata:Metadata={title:'Private Enterprise AI Solutions',description:'Secure company knowledge AI, SOP search, document intelligence, and AI automation.'};
const items=[
  {title:'Private AI Server',body:'A controlled AI environment designed around your security, performance, and governance requirements.',image:{src:'/ai-solutions/private-ai-server.webp',alt:'Private server secured inside a locked cabinet'}},
  {title:'Company Knowledge AI',body:'Turn internal documents, product information, policies, and expertise into a reliable knowledge layer.',image:{src:'/ai-solutions/company-knowledge-ai.webp',alt:'Organized company files and product knowledge connected to a central index'}},
  {title:'SOP Search',body:'Let employees ask precise operational questions and receive answers grounded in approved procedures.',image:{src:'/ai-solutions/sop-search.webp',alt:'Magnifying glass focused on an approved procedure binder'}},
  {title:'Employee Training AI',body:'Give new and experienced employees on-demand guidance based on company-specific knowledge.',image:{src:'/ai-solutions/employee-training-ai.webp',alt:'Employee using guided training materials on a tablet'}},
  {title:'Management AI Assistant',body:'Summarize information, investigate trends, and support faster, better-informed decisions.',image:{src:'/ai-solutions/management-ai-assistant.webp',alt:'Executive decision dashboard and management briefing materials'}},
  {title:'Document Intelligence',body:'Extract, compare, classify, and summarize information from business documents at scale.',image:{src:'/ai-solutions/document-intelligence.webp',alt:'Documents being sorted into classified information groups'}},
  {title:'AI Business Automation',body:'Connect intelligence to workflows so routine requests can trigger controlled, auditable actions.',image:{src:'/ai-solutions/ai-business-automation.webp',alt:'Connected workflow stations processing a business request'}},
];
const screenshots=[{src:'/showcase/open-webui/chat-dashboard.png',alt:'Private Open WebUI chat workspace with model and conversation controls',title:'Private AI workspace',description:'A secure, branded interface where your team can work with approved AI models and company knowledge.'},{src:'/showcase/open-webui/knowledge.png',alt:'Open WebUI knowledge base management screen',title:'Company knowledge',description:'Organize policies, procedures, product information, and reference material into governed knowledge collections.'},{src:'/showcase/open-webui/analytics.png',alt:'Open WebUI usage analytics dashboard',title:'Usage analytics',description:'Understand adoption, activity, and model usage across your private AI environment.'},{src:'/showcase/open-webui/model-editor.png',alt:'Open WebUI custom model configuration screen',title:'Purpose-built assistants',description:'Configure specialized assistants with the instructions, tools, and knowledge each role needs.'},{src:'/showcase/open-webui/notes.png',alt:'Open WebUI notes workspace',title:'Connected workspaces',description:'Capture, refine, and reuse important information without moving sensitive work across disconnected tools.'}];
export default function Page(){return <><SolutionPage eyebrow="PRIVATE ENTERPRISE AI" title="AI that knows your company—not the entire internet." intro="Nexavoris creates private enterprise AI systems grounded in your documents, SOPs, products, and operating knowledge. Deployments may run on dedicated customer hardware or controlled infrastructure depending on your requirements." items={items}/><ScreenshotGallery eyebrow="OPEN WEBUI SHOWCASE" title="A practical interface for private enterprise AI." intro="We configure Open WebUI around your models, knowledge, permissions, and operating requirements—giving employees a familiar workspace without sacrificing control." screenshots={screenshots}/></>}
