import type { Metadata } from 'next'; import { SolutionPage } from '@/components/solution-page'; import { ScreenshotGallery } from '@/components/screenshot-gallery';
export const metadata:Metadata={title:'ERP Consulting & Implementation',description:'ERP consulting, Odoo implementation, integration, migration, training, and support.'};
const names=['ERP Consulting & Workflow Design','Odoo Implementation','CRM & Sales','Purchasing & Inventory','Accounting Integration','Field Service','Subscriptions & Memberships','Dashboards & Reporting','Custom Modules','Third-Party Integrations','Data Migration & Training','Maintenance & Support']; const bodies=['Align technology decisions with how your business actually creates value.','Configure and extend Odoo as one capable platform within the right solution architecture.','Build a consistent process from first opportunity through quote, order, and relationship management.','Create visibility and control across suppliers, stock, replenishment, and fulfillment.','Connect operational workflows with your accounting system and financial processes.','Coordinate scheduling, technicians, work orders, parts, and customer communication.','Manage recurring revenue, renewals, access, and customer lifecycle processes.','Give leaders timely, trustworthy views of performance and exceptions.','Add the capabilities your operation needs without creating unnecessary complexity.','Connect existing platforms, commerce tools, payments, and specialized software.','Move critical records responsibly and prepare employees to work confidently.','Keep the system stable, relevant, and improving as your business evolves.'];
const images=[
  {src:'/erp-solutions/erp-consulting-workflow-design.webp',alt:'Consultants arranging a visual business workflow'},
  {src:'/erp-solutions/odoo-implementation.webp',alt:'Modular components forming a connected ERP platform'},
  {src:'/erp-solutions/crm-sales.webp',alt:'A customer relationship moving through a structured sales journey'},
  {src:'/erp-solutions/purchasing-inventory.webp',alt:'Purchase order, scanner, and inventory prepared for fulfillment'},
  {src:'/erp-solutions/accounting-integration.webp',alt:'Balanced operational and financial ledgers'},
  {src:'/erp-solutions/field-service.webp',alt:'Field technician coordinating work with tools, parts, and a tablet'},
  {src:'/erp-solutions/subscriptions-memberships.webp',alt:'Organized recurring membership and subscription lifecycle'},
  {src:'/erp-solutions/dashboards-reporting.webp',alt:'Executive performance dashboard and business reports'},
  {src:'/erp-solutions/custom-modules.webp',alt:'A tailored module fitted into a flexible business system'},
  {src:'/erp-solutions/third-party-integrations.webp',alt:'Commerce, payment, logistics, and business tools connected through one hub'},
  {src:'/erp-solutions/data-migration-training.webp',alt:'Business records moving safely into an organized system during employee training'},
  {src:'/erp-solutions/maintenance-support.webp',alt:'Specialist inspecting and maintaining precision system components'},
];
const screenshots=[{src:'/showcase/odoo/crm.webp',alt:'Odoo CRM pipeline dashboard',title:'CRM',description:'Track opportunities, priorities, and next actions across a clear visual sales pipeline.'},{src:'/showcase/odoo/sales.webp',alt:'Odoo sales quotation and order workspace',title:'Sales',description:'Move from quotation to order with consistent pricing, customer records, and approvals.'},{src:'/showcase/odoo/inventory.webp',alt:'Odoo inventory operations dashboard',title:'Inventory',description:'Coordinate receipts, deliveries, replenishment, and stock movements in one system.'},{src:'/showcase/odoo/manufacturing.webp',alt:'Odoo manufacturing planning interface',title:'Manufacturing',description:'Plan production, manage work orders, and connect materials to finished goods.'},{src:'/showcase/odoo/ecommerce.webp',alt:'Odoo ecommerce storefront and product page',title:'Ecommerce',description:'Connect the customer storefront directly to products, inventory, sales, and fulfillment.'}];
export default function Page(){return <><SolutionPage eyebrow="ERP SOLUTIONS" title="One source of truth for a business in motion." intro="Nexavoris designs and implements ERP systems that connect your teams, workflows, and data. We work with platforms including Odoo, while keeping the focus on the right long-term system for your operation." items={names.map((title,i)=>({title,body:bodies[i],image:images[i]}))}/><ScreenshotGallery eyebrow="ODOO SHOWCASE" title="One platform, connected across your operation." intro="Odoo brings customer, sales, inventory, manufacturing, ecommerce, and financial workflows together. We tailor the platform to the way your business actually works." screenshots={screenshots}/></>}
