import { ArrowRight, Database, Sparkles, Workflow, Users, BrainCircuit, Boxes, Search, ChartNoAxesCombined, FileText, GraduationCap, MonitorSmartphone, Wrench, Factory, Store, HardHat, Truck, Check } from 'lucide-react';
const layers=[{label:'Employees',icon:Users},{label:'Private AI',icon:BrainCircuit},{label:'ERP',icon:Boxes},{label:'Company Data',icon:Database},{label:'Automated Processes',icon:Workflow}];
const problems=['Hours lost searching for information','Critical procedures live with experienced employees','Data scattered across spreadsheets and software','No easy access to real-time management insight','Administrative work consumes skilled labor','Business systems do not communicate'];
const modules=['Sales','CRM','Purchasing','Inventory','Accounting integration','Field service','Project management','Employee management','Website','Memberships & subscriptions','Business reporting'];
const queries=["Show me last month's sales by salesperson.","Which customers haven't ordered in 60 days?","Create a quotation for this customer.","Which inventory items are running low?","Summarize today's outstanding deliveries.","Generate a purchasing recommendation."];
const automations=['Automatic quotations','Customer follow-up','Purchase order generation','Inventory alerts','Management reports','Recurring billing','Workflow approvals','Document processing'];
const industries=[['Wholesale & Distribution',Truck],['HVAC & Field Service',Wrench],['Construction',HardHat],['Retail',Store],['Manufacturing',Factory],['Professional Services',Users]];
const process=['Discovery','Business Process Analysis','System Design','Implementation','Data Migration','Employee Training','AI Integration','Ongoing Support'];
export default function Home(){return <main>
  <section className="hero section-shell"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> AI + ERP, engineered around your business</div><h1>AI That Understands<br/>Your Business.<br/><span>ERP That Runs It.</span></h1><p>Nexavoris combines private AI, enterprise knowledge, ERP systems and intelligent automation to help businesses operate faster, reduce administrative work and make better decisions.</p><div className="actions"><a className="button primary" href="/contact">Schedule a Consultation <ArrowRight size={17}/></a><a className="button secondary" href="#solutions">Explore Our Solutions</a></div><div className="trust-row"><span>PRIVATE BY DESIGN</span><span>BUSINESS-FIRST</span><span>BUILT FOR OPERATIONS</span></div></div>
  <div className="system-map"><div className="map-label">YOUR INTEGRATED OPERATING SYSTEM</div>{layers.map(({label,icon:Icon},i)=><div className="map-row" key={label} style={{animationDelay:`${i*120}ms`}}><div className="map-icon"><Icon size={18}/></div><span>{label}</span>{i<4&&<div className="map-flow"><i/></div>}</div>)}<div className="map-status"><i/> Systems connected · Knowledge active</div></div></section>
  <section className="section-shell intro" id="solutions"><div><span className="section-index">01 / THE OPPORTUNITY</span><h2>Turn operational complexity into a competitive advantage.</h2></div><p>Disconnected systems create friction. Nexavoris connects the knowledge your team relies on with the systems that move your business forward.</p></section>
  <section className="section-shell problem-grid">{problems.map((x,i)=><article key={x}><b>{String(i+1).padStart(2,'0')}</b><p>{x}</p></article>)}</section>
  <section className="band section-shell split"><div><span className="section-index">02 / PRIVATE ENTERPRISE AI</span><h2>Make your company knowledge accessible, secure, and useful.</h2><p>Build a private AI system around your internal documents, SOPs, product information, and business expertise. Deploy on dedicated customer hardware or controlled infrastructure based on your requirements.</p><a className="text-link" href="/ai-solutions">Explore AI solutions <ArrowRight size={16}/></a></div><div className="capability-list">{[[Search,'SOP & knowledge search'],[GraduationCap,'Employee training'],[ChartNoAxesCombined,'Management assistance'],[FileText,'Document analysis']].map(([I,t])=><div key={String(t)}>{typeof I!=='string'&&<I size={19}/>}<span>{String(t)}</span><Check size={15}/></div>)}</div></section>
  <section className="section-shell erp-section"><div className="section-head"><span className="section-index">03 / ERP SYSTEMS</span><h2>A connected platform for every part of your operation.</h2><p>We consult, implement, and customize modern ERP systems—including Odoo—without forcing your business into a one-size-fits-all model.</p></div><div className="module-cloud">{modules.map(m=><span key={m}>{m}</span>)}</div></section>
  <section className="integration" id="ai-erp"><div className="section-shell"><div className="section-head centered"><span className="section-index">04 / THE NEXAVORIS DIFFERENCE</span><h2>AI is more powerful when it can act on your business.</h2><p>Connect natural-language intelligence to real operational data across CRM, sales, inventory, purchasing, accounting, and operations.</p></div><div className="architecture"><div>EMPLOYEE</div><ArrowRight/><div className="active">AI ASSISTANT</div><ArrowRight/><div>ERP CORE</div><ArrowRight/><div className="nodes"><span>CRM</span><span>SALES</span><span>INVENTORY</span><span>OPERATIONS</span></div></div><div className="query-grid">{queries.map(q=><div key={q}><Sparkles size={14}/><span>“{q}”</span></div>)}</div><div className="center-action"><a className="button primary" href="/ai-erp">See AI + ERP in action <ArrowRight size={17}/></a></div></div></section>
  <section className="section-shell automation"><div className="section-head"><span className="section-index">05 / BUSINESS AUTOMATION</span><h2>Remove the repetitive work between systems.</h2></div><div>{automations.map(a=><span key={a}><Check size={14}/>{a}</span>)}</div></section>
  <section className="band section-shell split website-band"><div><span className="section-index">06 / WEBSITE DESIGN</span><h2>A polished digital presence, connected to your business.</h2><p>Strategy, design, development, ecommerce, and integrations in one practical engagement—with clear packages starting at $2,500.</p><a className="text-link" href="/website-design">Explore website design & pricing <ArrowRight size={16}/></a></div><div className="website-preview"><MonitorSmartphone size={42}/><strong>Designed to earn trust.</strong><span>Built to convert. Ready to grow.</span></div></section>
  <section className="section-shell industries"><div className="section-head"><span className="section-index">07 / INDUSTRIES</span><h2>Built for companies where operations matter.</h2></div><div className="industry-grid">{industries.map(([name,I])=><a href="/industries" key={String(name)}><I size={23}/><span>{String(name)}</span><ArrowRight size={16}/></a>)}</div></section>
  <section className="process" id="process"><div className="section-shell"><div className="section-head"><span className="section-index">08 / IMPLEMENTATION</span><h2>A disciplined path from complexity to clarity.</h2></div><div className="process-track">{process.map((p,i)=><div key={p}><b>{String(i+1).padStart(2,'0')}</b><span>{p}</span></div>)}</div></div></section>
  <section className="section-shell why"><div><span className="section-index">09 / WHY NEXAVORIS</span><h2>Technology designed around business outcomes.</h2></div><div>{['Business-first approach','Private enterprise AI','Integrated AI + ERP architecture','Long-term implementation support'].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div></section>
  <section className="cta"><div className="section-shell"><span className="section-index">START THE CONVERSATION</span><h2>Your business already has the data.<br/>Nexavoris helps you put it to work.</h2><a className="button primary" href="/contact">Schedule a Consultation <ArrowRight size={17}/></a></div></section>
 </main>}
