'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, BarChart3, BookOpen, Download, FileUp, Globe2, Link2, LogOut, SearchCheck, ShieldCheck, Target } from 'lucide-react';

type Row = Record<string, any>;
const sections = ['overview','keywords','google','indexing','google-ai','chatgpt','bing','backlinks','conversions','tasks','reports'];
const labels: Row = { overview:'Overview', keywords:'Keywords', google:'Google Search', indexing:'Indexing', 'google-ai':'Google AI', chatgpt:'ChatGPT', bing:'Bing / Copilot', backlinks:'Backlinks', conversions:'Conversions', tasks:'Tasks', reports:'Reports' };
const today = new Date().toISOString().slice(0, 10);
const Field = ({label,children}:{label:string;children:any}) => <label className="seo-field"><span>{label}</span>{children}</label>;
const StatusSelect = ({name='status'}:{name?:string}) => <select name={name} defaultValue="Unknown"><option>Unknown</option><option>Yes</option><option>No</option></select>;

export function SeoGeoControlCenter({actor,initialTab='overview'}:{actor:Row;initialTab?:string}) {
  const [data,setData] = useState<Row|null>(null), [tab,setTab] = useState(initialTab), [message,setMessage] = useState('');
  const load = () => fetch('/api/admin/seo-geo').then(async r => { const j=await r.json() as Row; if(!r.ok) throw new Error(j.error); return j; }).then((value)=>setData(value)).catch(e=>setMessage(e.message||'Unable to load data.'));
  useEffect(()=>{ void load(); },[]);
  const save = async (body:Row) => { setMessage('Saving…'); const r=await fetch('/api/admin/seo-geo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const j=await r.json().catch(()=>({})) as Row; setMessage(r.ok?'Saved securely.':j.error||'Unable to save.'); if(r.ok) await load(); return r.ok; };
  const submit = (action:string) => (event:any) => { event.preventDefault(); const form=event.currentTarget, body:Row={action}; new FormData(form).forEach((v,k)=>body[k]=v); void save(body).then(ok=>{if(ok) form.reset()}); };
  if(!data) return <main className="admin-loading"><ShieldCheck/><p>{message||'Loading SEO + GEO Control Center…'}</p></main>;
  return <main className="admin-shell seo-admin">
    <aside className="admin-sidebar"><div><SearchCheck/><b>Nexavoris Admin</b><small>SEO + GEO Control Center</small></div><nav><a href="/admin"><ArrowLeft size={17}/>Admin dashboard</a>{sections.map(id=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{id==='overview'?<BarChart3 size={17}/>:id==='keywords'?<Target size={17}/>:id==='backlinks'?<Link2 size={17}/>:id==='reports'?<BookOpen size={17}/>:<Globe2 size={17}/>} {labels[id]}</button>)}</nav><a href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={16}/>Sign out</a></aside>
    <section className="admin-main"><header><div><span>PRIVATE · ADMIN ONLY</span><h1>Nexavoris SEO + GEO Control Center</h1></div><div className="admin-identity">{actor.name||actor.email}<small>{actor.email}</small></div></header>{message&&<div className="admin-toast">{message}</div>}
      {tab==='overview'&&<Overview data={data}/>} {tab==='keywords'&&<Keywords data={data} save={save} submit={submit('keyword_save')}/>} {tab==='google'&&<Google data={data} save={save} submit={submit('ranking_add')}/>} {tab==='indexing'&&<Indexing data={data} save={save}/>} {tab==='google-ai'&&<Geo data={data} platform="Google AI" submit={submit('geo_add')}/>} {tab==='chatgpt'&&<Geo data={data} platform="ChatGPT" submit={submit('geo_add')}/>} {tab==='bing'&&<Geo data={data} platform="Bing/Copilot" submit={submit('geo_add')}/>} {tab==='backlinks'&&<Backlinks data={data} submit={submit}/>} {tab==='conversions'&&<Conversions data={data}/>} {tab==='tasks'&&<TaskList data={data} save={save}/>} {tab==='reports'&&<Reports data={data}/>}
    </section>
  </main>;
}

function Metric({label,value,suffix=''}:{label:string;value:any;suffix?:string}) { return <article className="admin-metric"><span>{label}</span><strong>{value===null||value===undefined?'No data yet':`${value}${suffix}`}</strong></article>; }
function Overview({data}:{data:Row}) { const s=data.summary; return <><section className="seo-exec">{[['SEARCH VISIBILITY',s.searchImpressions?`${s.searchImpressions} impressions`:'No data yet'],['BRAND VISIBILITY',data.scores.branded],['AI ERP VISIBILITY',data.scores.competitive],['GEO CITATIONS',s.chatgptCitations+s.googleAiMentions+s.copilotMentions||'No data yet'],['AUTHORITY',s.referringDomains?`${s.referringDomains} domains`:'No data yet'],['CONVERSIONS',s.organicRegistrations+s.organicConsultations||'No data yet']].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</section><div className="admin-metrics"><Metric label="Google indexed pages" value={s.indexedPages}/><Metric label="Google search impressions" value={s.searchImpressions}/><Metric label="Google search clicks" value={s.searchClicks}/><Metric label="Average Google position" value={s.averagePosition}/><Metric label="Google CTR" value={s.ctr} suffix="%"/><Metric label="Google AI mentions" value={s.googleAiMentions}/><Metric label="ChatGPT mentions" value={s.chatgptMentions}/><Metric label="ChatGPT citations" value={s.chatgptCitations}/><Metric label="Bing indexed pages" value={s.bingIndexedPages}/><Metric label="Bing average position" value={s.bingAveragePosition}/><Metric label="Copilot mentions" value={s.copilotMentions}/><Metric label="Referring domains" value={s.referringDomains}/><Metric label="Backlinks" value={s.backlinks}/><Metric label="Organic registrations" value={s.organicRegistrations}/><Metric label="Organic consultations" value={s.organicConsultations}/></div><div className="admin-grid"><section className="admin-card"><h2>Striking distance opportunities</h2>{data.striking.length?data.striking.slice(0,5).map((r:Row)=><div className="seo-list-row" key={r.id}><span><b>{r.keyword}</b><small>{r.target_url} · {r.impressions} impressions</small></span><strong>#{r.position}</strong></div>):<p>No ranking data between positions 8 and 30 yet. Enter a Google ranking observation.</p>}</section><section className="admin-card"><h2>Priority action engine</h2><ActionList data={data}/></section></div></>; }
function ActionList({data}:{data:Row}) { const actions:string[]=[]; for(const r of data.striking.slice(0,5)) actions.push(Number(r.position)<=15?`${r.keyword}: improve CTR, answer depth, internal links, and authority.`:`${r.keyword}: strengthen the page, supporting cluster, links, and evidence.`); if(!data.gsc.length)actions.push('Import Search Console data to identify impressions, CTR, and average position.'); if(!data.geo.length)actions.push('Record a current ChatGPT, Google AI, or Copilot test.'); if(!data.backlinks.length)actions.push('Add verified authority and backlink observations.'); return <ol className="seo-actions">{actions.slice(0,5).map(x=><li key={x}>{x}</li>)}</ol>; }

function Keywords({data,save,submit}:{data:Row;save:(x:Row)=>void;submit:any}) { return <><form className="seo-form" onSubmit={submit}><h2>Add target keyword</h2><Field label="Keyword"><input name="keyword" required/></Field><Field label="Category"><select name="category"><option>Branded</option><option>Core</option><option>Industry</option><option>Buyer</option></select></Field><Field label="Target URL"><input name="targetUrl" placeholder="/ai-erp" required/></Field><Field label="Priority"><select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></Field><button>Add keyword</button></form><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Keyword</th><th>Category</th><th>Target</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.keywords.map((k:Row)=><tr key={k.id}><td><input defaultValue={k.keyword} onBlur={e=>k._keyword=e.target.value}/></td><td><select defaultValue={k.category} onChange={e=>k._category=e.target.value}><option>Branded</option><option>Core</option><option>Industry</option><option>Buyer</option></select></td><td><input defaultValue={k.target_url} onBlur={e=>k._target=e.target.value}/></td><td><select defaultValue={k.priority} onChange={e=>k._priority=e.target.value}><option>High</option><option>Medium</option><option>Low</option></select></td><td>{k.active?'Active':'Inactive'}</td><td><button onClick={()=>save({action:'keyword_save',id:k.id,keyword:k._keyword||k.keyword,category:k._category||k.category,targetUrl:k._target||k.target_url,priority:k._priority||k.priority,active:Boolean(k.active)})}>Save</button> <button className="secondary" onClick={()=>save({action:'keyword_save',id:k.id,keyword:k.keyword,category:k.category,targetUrl:k.target_url,priority:k.priority,active:!k.active})}>{k.active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></>; }

function Google({data,save,submit}:{data:Row;save:(x:Row)=>Promise<boolean>;submit:any}) { const [keyword,setKeyword]=useState(data.keywords[0]?.id||''), selected=data.keywords.find((x:Row)=>x.id===keyword), history=data.rankings.filter((x:Row)=>x.keyword_id===keyword); const importCsv=async(file:File)=>{const text=await file.text(),lines=text.trim().split(/\r?\n/),headers=(lines.shift()||'').split(',').map(x=>x.trim().toLowerCase()),rows=lines.filter(Boolean).map(line=>{const values=(line.match(/("[^"]*(?:""[^"]*)*"|[^,]*)(?:,|$)/g)||[]).map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replaceAll('""','"'));return Object.fromEntries(headers.map((h,i)=>[h,values[i]||'']))});await save({action:'gsc_import',rows});}; return <><div className="admin-grid"><form className="seo-form" onSubmit={submit}><h2>Google Search Rankings</h2><Field label="Date"><input type="date" name="date" defaultValue={today} required/></Field><Field label="Keyword"><select name="keywordId" value={keyword} onChange={e=>setKeyword(e.target.value)}>{data.keywords.filter((x:Row)=>x.active).map((x:Row)=><option value={x.id} key={x.id}>{x.keyword}</option>)}</select></Field><input type="hidden" name="targetUrl" value={selected?.target_url||''}/><Field label="Google position"><input type="number" min="1" step="0.1" name="position" required/></Field><Field label="Actual ranking URL"><input name="actualUrl" placeholder="/ai-erp"/></Field><Field label="Result page"><input type="number" min="1" name="resultPage"/></Field><Field label="Country"><input name="country" placeholder="United States"/></Field><Field label="Language"><input name="language" placeholder="English"/></Field><Field label="Device"><select name="device"><option>Desktop</option><option>Mobile</option><option>Tablet</option></select></Field><Field label="Notes"><textarea name="notes"/></Field><button>Save historical observation</button></form><section className="admin-card"><h2>{selected?.keyword||'Keyword'} history</h2><p>Manual rankings remain separate from Search Console average position.</p><Trend rows={history}/></section></div><section className="admin-card"><h2>Google Search Console</h2><div className="seo-toolbar"><label className="export-button"><FileUp size={15}/>Import Search Console CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&void importCsv(e.target.files[0])}/></label><a className="export-button secondary" href="/api/admin/seo-geo?export=gsc"><Download size={15}/>Export SEO metrics</a></div><p>CSV headers: <code>date,query,page,clicks,impressions,ctr,position,country,device</code>. Imports append history and retain their source label.</p>{data.gsc.length?<DataTable rows={data.gsc.slice(0,100)} columns={['metric_date','query','page','clicks','impressions','ctr','average_position','country','device','source_type']}/>:<p className="seo-empty">No Search Console data yet. Import Data.</p>}</section></>; }

function Trend({rows}:{rows:Row[]}) { if(!rows.length)return <p className="seo-empty">No ranking history yet.</p>; const ordered=[...rows].reverse(),max=Math.max(...ordered.map(x=>Number(x.position))); return <div className="seo-trend" aria-label="Ranking history chart">{ordered.slice(-12).map(r=><div key={r.id}><i style={{height:`${Math.max(8,(1-Number(r.position)/(max+5))*100)}%`}}/><small>{r.position}</small><span>{String(r.checked_date).slice(5)}</span></div>)}</div>; }

function Indexing({data,save}:{data:Row;save:(x:Row)=>void}) { return <section className="admin-card"><h2>Google Indexing Status</h2><p>Routes are preloaded from the public sitemap plan. Update only from Google URL Inspection evidence.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>URL</th><th>Indexed</th><th>Expected canonical</th><th>Google canonical</th><th>Last checked</th><th>Flags</th><th>Action</th></tr></thead><tbody>{data.indexing.map((r:Row)=><tr key={r.url}><td>{r.url}</td><td><select defaultValue={r.indexed_status} onChange={e=>r._status=e.target.value}><option>Unknown</option><option>Yes</option><option>No</option></select></td><td>{r.expected_canonical}</td><td><input defaultValue={r.google_canonical||''} onBlur={e=>r._canonical=e.target.value}/></td><td><input type="date" defaultValue={r.last_checked||today} onChange={e=>r._date=e.target.value}/></td><td>{r.indexed_status==='No'?'Expected indexed but not indexed':r.google_canonical&&r.google_canonical!==r.expected_canonical?'Canonical mismatch':!r.in_sitemap?'Missing sitemap URL':'—'}</td><td><button onClick={()=>save({action:'indexing_save',url:r.url,indexedStatus:r._status||r.indexed_status,googleCanonical:r._canonical??r.google_canonical,date:r._date||r.last_checked||today,notes:r.notes||''})}>Save</button></td></tr>)}</tbody></table></div></section>; }

function Geo({data,platform,submit}:{data:Row;platform:string;submit:any}) { const rows=data.geo.filter((r:Row)=>r.platform===platform); return <><form className="seo-form" onSubmit={submit}><h2>{platform} Visibility</h2><input type="hidden" name="platform" value={platform}/><Field label="Date"><input type="date" name="date" defaultValue={today} required/></Field><Field label="Prompt / query"><textarea name="prompt" required/></Field><Field label="Related keyword"><input name="keyword"/></Field>{platform==='Bing/Copilot'&&<Field label="Bing position"><input type="number" min="1" name="position"/></Field>}<Field label="Nexavoris mentioned?"><StatusSelect name="mentioned"/></Field><Field label="Nexavoris cited?"><StatusSelect name="cited"/></Field><Field label="Cited URL"><input name="citedUrl"/></Field><Field label="Correct description?"><StatusSelect name="correctDescription"/></Field><Field label="Competitors shown"><textarea name="competitors"/></Field><Field label="Screenshot/reference notes"><textarea name="notes"/></Field><button>Record test</button></form><section className="admin-card"><div className="seo-toolbar"><h2>Historical tests</h2><a className="export-button secondary" href="/api/admin/seo-geo?export=geo"><Download size={15}/>Export GEO tests</a></div>{rows.length?<DataTable rows={rows} columns={['checked_date','prompt','mentioned','cited','cited_url','correct_description','position_value','competitors','source_type','checked_by']}/>:<p className="seo-empty">No {platform} observations yet. Record GEO Test.</p>}</section></>; }

function Backlinks({data,submit}:{data:Row;submit:(x:string)=>any}) { return <><div className="admin-grid"><form className="seo-form" onSubmit={submit('backlink_add')}><h2>Authority & Backlinks</h2><Field label="Referring domain"><input name="domain" required/></Field><Field label="Source URL"><input type="url" name="sourceUrl" required/></Field><Field label="Target Nexavoris URL"><input name="targetUrl" required/></Field><Field label="First discovered"><input type="date" name="date" defaultValue={today}/></Field><Field label="Link type"><select name="linkType"><option>Unknown</option><option>Follow</option><option>NoFollow</option></select></Field><Field label="Industry"><input name="industry"/></Field><Field label="Status"><select name="status"><option>Active</option><option>Lost</option><option>Pending</option><option>Outreach</option><option>Rejected</option></select></Field><Field label="Authority notes"><textarea name="authorityNotes"/></Field><Field label="Notes / evidence"><textarea name="notes"/></Field><button>Add backlink</button></form><form className="seo-form" onSubmit={submit('profile_add')}><h2>External Business Profile</h2><Field label="Platform"><select name="platform"><option>Google Business Profile</option><option>LinkedIn</option><option>GitHub</option><option>Bing Places</option><option>Industry directory</option><option>Business association</option><option>Partner profile</option><option>Media mention</option></select></Field><Field label="Profile URL"><input type="url" name="profileUrl" required/></Field><Field label="Verified?"><StatusSelect name="verified"/></Field><Field label="Backlink?"><StatusSelect name="backlink"/></Field><Field label="Date created"><input type="date" name="date"/></Field><Field label="Status"><input name="status"/></Field><Field label="Notes"><textarea name="notes"/></Field><button>Add profile</button></form></div><section className="admin-card"><div className="seo-toolbar"><h2>Recorded backlinks</h2><a className="export-button secondary" href="/api/admin/seo-geo?export=backlinks"><Download size={15}/>Export backlinks</a></div>{data.backlinks.length?<DataTable rows={data.backlinks} columns={['referring_domain','source_url','target_url','first_discovered','link_type','industry','status','source_type','checked_by']}/>:<p className="seo-empty">No backlink data yet. Add Backlink.</p>}</section><section className="admin-card"><h2>Authority profiles</h2>{data.profiles.length?<DataTable rows={data.profiles} columns={['platform','profile_url','verified_status','backlink_status','created_date','status','checked_by']}/>:<p className="seo-empty">No external profiles recorded yet.</p>}</section></>; }

function Conversions({data}:{data:Row}) { const count=(name:string)=>data.organicEvents.filter((e:Row)=>e.event_name===name).length; const stages=[['Organic Search Visitor',count('organic_visit')],['Assessment Start',count('assessment_started')],['Assessment Complete',count('assessment_completed')],['Free Registration',data.summary.organicRegistrations],['Roadmap Generated',count('roadmap_generated')],['Consultation',data.summary.organicConsultations],['Client',count('client_converted')]]; return <><section className="admin-card"><h2>Search → Conversion Funnel</h2><p>Only events with an explicit organic source/referrer label are included. Unknown acquisition sources are not guessed.</p><div className="seo-funnel">{stages.map(([label,value],i)=><div key={String(label)}><span>{i?'↓':''}</span><b>{value}</b><small>{label}</small></div>)}</div></section><section className="admin-card"><h2>Internal analytics evidence</h2>{data.organicEvents.length?<DataTable rows={data.organicEvents} columns={['created_at','event_name','context_json']}/>:<p className="seo-empty">No explicitly attributed organic events yet. Conversion score remains insufficient data.</p>}</section></>; }

function TaskList({data,save}:{data:Row;save:(x:Row)=>void}) { return <section className="admin-card"><h2>Manual Test Task List</h2><p>Recommended cadence: Search Console, target rankings, indexing, striking distance, and conversions weekly; GEO, Bing/Copilot, backlinks, and profiles monthly.</p>{data.tasks.map((t:Row)=><div className="seo-task" key={t.id}><div><b>{t.title}</b><small>{t.cadence} · {t.task_type}</small></div><select defaultValue={t.status} onChange={e=>t._status=e.target.value}><option>Pending</option><option>Complete</option><option>Skipped</option></select><input type="date" defaultValue={t.checked_date||today} onChange={e=>t._date=e.target.value}/><input placeholder="Result" defaultValue={t.result||''} onBlur={e=>t._result=e.target.value}/><input placeholder="Notes" defaultValue={t.notes||''} onBlur={e=>t._notes=e.target.value}/><button onClick={()=>save({action:'task_save',id:t.id,status:t._status||t.status,date:t._date||t.checked_date||today,result:t._result??t.result,notes:t._notes??t.notes})}>Save</button></div>)}</section>; }

function Reports({data}:{data:Row}) { return <><section className="admin-card"><h2>Monthly Scorecard</h2><p>Scores appear only after the minimum documented evidence threshold is met. Readiness is never presented as ranking.</p><div className="admin-metrics"><Metric label="SEO visibility score /100" value={data.scores.seo}/><Metric label="GEO visibility score /100" value={data.scores.geo}/><Metric label="Branded search score /100" value={data.scores.branded}/><Metric label="AI ERP competitiveness /100" value={data.scores.competitive}/><Metric label="Conversion score /100" value={data.scores.conversion}/></div></section><section className="admin-card"><h2>AI ERP Competitive Score</h2><div className="admin-metrics"><Metric label="Technical readiness" value="Verified in deployment audit"/><Metric label="Content readiness" value="Tracked separately"/><Metric label="Authority" value={data.backlinks.length?`${data.summary.referringDomains} referring domains`:'Insufficient data'}/><Metric label="Actual visibility" value={data.scores.competitive}/></div></section><div className="admin-grid"><section className="admin-card"><h2>Top keyword gains</h2>{data.weekly.gains.length?data.weekly.gains.map((x:Row)=><div className="seo-list-row" key={x.keyword}><b>{x.keyword}</b><span>{x.previous} → {x.current} (+{x.change})</span></div>):<p>Insufficient ranking history.</p>}</section><section className="admin-card"><h2>Top keyword losses</h2>{data.weekly.losses.length?data.weekly.losses.map((x:Row)=><div className="seo-list-row" key={x.keyword}><b>{x.keyword}</b><span>{x.previous} → {x.current} ({x.change})</span></div>):<p>Insufficient ranking history.</p>}</section></div><section className="admin-card"><h2>Weekly Review</h2><p>{data.gsc.length?'Stored Search Console rows are ready for dated review.':'Insufficient data. Import at least two dated Search Console periods.'}</p><ActionList data={data}/></section><section className="admin-card"><h2>Documented score rules</h2><p>SEO requires at least seven Search Console rows and weights data presence, clicks, CTR, and verified index coverage. GEO requires five tests and scores observed mentions plus citations. Branded and AI ERP scores require at least three latest keyword observations and use position-based visibility; AI ERP adds only recorded referring-domain authority. Conversion requires five explicitly organic events. Otherwise the result is “Insufficient data.”</p></section><section className="admin-card"><h2>Data confidence</h2><p>Every stored row is labeled as GOOGLE SEARCH CONSOLE, MANUAL GOOGLE SEARCH, MANUAL GOOGLE AI TEST, MANUAL CHATGPT TEST, MANUAL BING TEST, INTERNAL ANALYTICS, or MANUAL BACKLINK ENTRY. Manual observations are never mixed silently with API-derived metrics.</p></section></>; }

function DataTable({rows,columns}:{rows:Row[];columns:string[]}) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c}>{String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div>; }
