import { requireAdminActor } from '@/lib/admin-auth';
import { ensureMemberSchema, memberDB, parseJSON } from '@/lib/member-db';
import { ensureSeoGeoSeed } from '@/lib/seo-geo-data';

export const dynamic='force-dynamic';
type Row=Record<string,any>;
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const clean=(v:unknown,max=2000)=>String(v??'').trim().slice(0,max);
const yn=(v:unknown)=>['Yes','No','Unknown'].includes(String(v))?String(v):'Unknown';
const num=(v:unknown)=>v===''||v===null||v===undefined?null:Number(v);
const csv=(rows:Row[],columns:string[])=>[columns.join(','),...rows.map(row=>columns.map(k=>`"${String(row[k]??'').replaceAll('"','""')}"`).join(','))].join('\r\n');

async function ready(){await ensureMemberSchema();await ensureSeoGeoSeed();return memberDB()}
async function audit(actorId:string,action:string,detail:Row){await memberDB().prepare("INSERT INTO admin_audit_log (id,actor_user_id,target_user_id,action,detail_json,created_at) VALUES (?,?,NULL,?,?,?)").bind(crypto.randomUUID(),actorId,action,JSON.stringify(detail),new Date().toISOString()).run()}

export async function GET(request:Request){
  const actor=await requireAdminActor('admin'); if(!actor)return json({error:'Administrator access required'},403);
  const db=await ready(), url=new URL(request.url), format=url.searchParams.get('export');
  const tables:Record<string,{sql:string,columns:string[]}>= {
    keywords:{sql:'SELECT * FROM seo_keywords ORDER BY active DESC,category,keyword',columns:['keyword','category','target_url','priority','active','created_at','updated_at']},
    rankings:{sql:'SELECT r.*,k.keyword,k.category,k.priority FROM seo_google_rankings r JOIN seo_keywords k ON k.id=r.keyword_id ORDER BY checked_date DESC,created_at DESC',columns:['checked_date','keyword','position','target_url','actual_url','result_page','country','language','device','notes','source_type']},
    gsc:{sql:'SELECT * FROM seo_gsc_metrics ORDER BY metric_date DESC',columns:['metric_date','query','page','clicks','impressions','ctr','average_position','country','device','source_type']},
    geo:{sql:'SELECT * FROM seo_geo_tests ORDER BY checked_date DESC',columns:['platform','checked_date','prompt','keyword','mentioned','cited','cited_url','correct_description','position_value','competitors','notes','source_type']},
    backlinks:{sql:'SELECT * FROM seo_backlinks ORDER BY first_discovered DESC',columns:['referring_domain','source_url','target_url','first_discovered','link_type','industry','status','authority_notes','notes','source_type']},
  };
  if(format&&tables[format]){const {results}=await db.prepare(tables[format].sql).all<Row>();return new Response(csv(results,tables[format].columns),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="nexavoris-${format}.csv"`,'Cache-Control':'no-store'}})}
  const [keywords,rankings,gsc,indexing,geo,backlinks,profiles,tasks,events,consultations,clients]=await Promise.all([
    db.prepare(tables.keywords.sql).all<Row>(),db.prepare(tables.rankings.sql+' LIMIT 500').all<Row>(),db.prepare(tables.gsc.sql+' LIMIT 2000').all<Row>(),db.prepare('SELECT * FROM seo_indexing_status ORDER BY url').all<Row>(),db.prepare(tables.geo.sql+' LIMIT 1000').all<Row>(),db.prepare(tables.backlinks.sql+' LIMIT 1000').all<Row>(),db.prepare('SELECT * FROM seo_authority_profiles ORDER BY platform').all<Row>(),db.prepare('SELECT * FROM seo_manual_tasks ORDER BY status,due_date,title').all<Row>(),db.prepare('SELECT event_name,context_json,created_at FROM member_events ORDER BY created_at DESC').all<Row>(),db.prepare('SELECT id,user_id,created_at FROM consultation_requests ORDER BY created_at DESC').all<Row>(),db.prepare("SELECT count(*) count FROM member_admin_records WHERE client_tier='Client'").first<Row>()]);
  const organicEvents=(events.results??[]).filter(e=>{const c=parseJSON<Row>(e.context_json,{});return ['organic','organic search','google','bing'].includes(String(c.source??c.trafficSource??c.referrerType??'').toLowerCase())});
  const sums=(gsc.results??[]).reduce((a,r)=>({clicks:a.clicks+Number(r.clicks||0),impressions:a.impressions+Number(r.impressions||0),weighted:a.weighted+Number(r.average_position||0)*Number(r.impressions||0)}),{clicks:0,impressions:0,weighted:0});
  const latest=new Map<string,Row>(); for(const r of rankings.results??[])if(!latest.has(r.keyword_id))latest.set(r.keyword_id,r);
  const striking:Row[]=[...latest.values()].filter(r=>Number(r.position)>=8&&Number(r.position)<=30).map(r=>({...r,impressions:(gsc.results??[]).filter(x=>String(x.query).toLowerCase()===String(r.keyword).toLowerCase()).reduce((s,x)=>s+Number(x.impressions||0),0)} as Row)).sort((a,b)=>Number(a.position)-Number(b.position));
  const activeLinks=(backlinks.results??[]).filter(x=>x.status==='Active');
  const hasGsc=(gsc.results??[]).length>0, hasGeo=(geo.results??[]).length>0, hasBacklinks=(backlinks.results??[]).length>0, hasOrganic=organicEvents.length>0, knownIndexRows=(indexing.results??[]).filter(x=>x.indexed_status!=='Unknown');
  const summary={indexedPages:knownIndexRows.length?(indexing.results??[]).filter(x=>x.indexed_status==='Yes').length:null,searchImpressions:hasGsc?sums.impressions:null,searchClicks:hasGsc?sums.clicks:null,averagePosition:sums.impressions?Number((sums.weighted/sums.impressions).toFixed(1)):null,ctr:sums.impressions?Number((sums.clicks/sums.impressions*100).toFixed(2)):null,googleAiMentions:hasGeo?(geo.results??[]).filter(x=>x.platform==='Google AI'&&x.mentioned==='Yes').length:null,chatgptMentions:hasGeo?(geo.results??[]).filter(x=>x.platform==='ChatGPT'&&x.mentioned==='Yes').length:null,chatgptCitations:hasGeo?(geo.results??[]).filter(x=>x.platform==='ChatGPT'&&x.cited==='Yes').length:null,bingIndexedPages:null,bingAveragePosition:null,copilotMentions:hasGeo?(geo.results??[]).filter(x=>x.platform==='Bing/Copilot'&&x.mentioned==='Yes').length:null,referringDomains:hasBacklinks?new Set(activeLinks.map(x=>x.referring_domain)).size:null,backlinks:hasBacklinks?activeLinks.length:null,organicRegistrations:hasOrganic?organicEvents.filter(x=>x.event_name==='registration_completed').length:null,organicConsultations:hasOrganic?organicEvents.filter(x=>x.event_name==='consultation_submitted').length:null};
  const rankScore=(rows:Row[])=>Math.round(rows.reduce((sum,r)=>sum+Math.max(0,100-(Number(r.position)-1)*3),0)/Math.max(1,rows.length));
  const branded=[...latest.values()].filter(x=>x.category==='Branded'), competitive=[...latest.values()].filter(x=>x.category==='Core');
  const enough={seo:(gsc.results??[]).length>=7,geo:(geo.results??[]).length>=5,branded:branded.length>=3,competitive:competitive.length>=3,conversion:organicEvents.length>=5};
  const knownIndex=(indexing.results??[]).filter(x=>x.indexed_status!=='Unknown'), indexedRatio=knownIndex.length?knownIndex.filter(x=>x.indexed_status==='Yes').length/knownIndex.length:0;
  const geoRows=geo.results??[], geoPositive=geoRows.filter(x=>x.mentioned==='Yes').length+geoRows.filter(x=>x.cited==='Yes').length;
  const scores={seo:enough.seo?Math.round(Math.min(100,20+(sums.impressions>0?20:0)+(sums.clicks>0?20:0)+(Number(summary.ctr)>=2?20:10)+indexedRatio*20)):'Insufficient data',geo:enough.geo?Math.round(geoPositive/(geoRows.length*2)*100):'Insufficient data',branded:enough.branded?rankScore(branded):'Insufficient data',competitive:enough.competitive?Math.round(rankScore(competitive)*.7+Math.min(30,Number(summary.referringDomains??0)*3)):'Insufficient data',conversion:enough.conversion?Math.round(Math.min(100,(Number(summary.organicConsultations)/Math.max(1,Number(summary.organicRegistrations)))*70+(organicEvents.filter(x=>x.event_name==='assessment_completed').length/organicEvents.length)*30)):'Insufficient data'};
  const byKeyword=new Map<string,Row[]>();for(const r of rankings.results??[]){const list=byKeyword.get(r.keyword_id)||[];list.push(r);byKeyword.set(r.keyword_id,list)}
  const changes=[...byKeyword.values()].filter(rows=>rows.length>1).map(rows=>({keyword:rows[0].keyword,current:Number(rows[0].position),previous:Number(rows[1].position),change:Number(rows[1].position)-Number(rows[0].position)}));
  const weekly={gains:changes.filter(x=>x.change>0).sort((a,b)=>b.change-a.change).slice(0,5),losses:changes.filter(x=>x.change<0).sort((a,b)=>a.change-b.change).slice(0,5)};
  return json({actor,summary,keywords:keywords.results,rankings:rankings.results,gsc:gsc.results,indexing:indexing.results,geo:geo.results,backlinks:backlinks.results,profiles:profiles.results,tasks:tasks.results,striking,organicEvents,consultationCount:(consultations.results??[]).length,clientCount:Number(clients?.count??0),scores,weekly})
}

export async function POST(request:Request){
  const actor=await requireAdminActor('admin'); if(!actor)return json({error:'Administrator access required'},403);
  const db=await ready(), body=await request.json() as Row, action=clean(body.action,50), now=new Date().toISOString(), id=crypto.randomUUID();
  try{
    if(action==='keyword_save'){
      const keyword=clean(body.keyword,200), category=clean(body.category,20), target=clean(body.targetUrl,500), priority=clean(body.priority,10);if(!keyword||!target||!['Branded','Core','Industry','Buyer'].includes(category)||!['High','Medium','Low'].includes(priority))return json({error:'Valid keyword, category, target URL, and priority are required'},400);
      if(body.id)await db.prepare('UPDATE seo_keywords SET keyword=?,category=?,target_url=?,priority=?,active=?,updated_at=? WHERE id=?').bind(keyword,category,target,priority,body.active===false?0:1,now,body.id).run();else await db.prepare('INSERT INTO seo_keywords (id,keyword,category,target_url,priority,active,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?)').bind(id,keyword,category,target,priority,now,now).run();
    } else if(action==='ranking_add'){
      const position=num(body.position),keywordId=clean(body.keywordId,100);if(!keywordId||position===null||position<1||position>1000)return json({error:'Keyword and a positive position are required'},400);
      await db.prepare("INSERT INTO seo_google_rankings (id,keyword_id,checked_date,position,target_url,actual_url,result_page,country,language,device,notes,checked_by,source_type,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'MANUAL GOOGLE SEARCH',?)").bind(id,keywordId,clean(body.date,10),position,clean(body.targetUrl,500),clean(body.actualUrl,500)||null,num(body.resultPage),clean(body.country,100)||null,clean(body.language,50)||null,clean(body.device,50)||null,clean(body.notes),actor.email,now).run();
    } else if(action==='gsc_import'){
      const rows=Array.isArray(body.rows)?body.rows.slice(0,5000):[];if(!rows.length)return json({error:'No valid Search Console rows supplied'},400);
      const statements=rows.map((r:Row)=>{const clicks=Math.max(0,Number(r.clicks||0)),impressions=Math.max(0,Number(r.impressions||0)),ctr=Number(String(r.ctr??0).replace('%','')),position=num(r.position??r.average_position);if(!clean(r.date,10)||!clean(r.query,500)||!clean(r.page,1000)||!Number.isFinite(clicks)||!Number.isFinite(impressions)||!Number.isFinite(ctr))throw new Error('CSV contains invalid required values');return db.prepare("INSERT INTO seo_gsc_metrics (id,metric_date,query,page,clicks,impressions,ctr,average_position,country,device,source_type,imported_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?, 'GOOGLE SEARCH CONSOLE',?,?)").bind(crypto.randomUUID(),clean(r.date,10),clean(r.query,500),clean(r.page,1000),clicks,impressions,ctr,position,clean(r.country,100)||null,clean(r.device,50)||null,actor.email,now)});await db.batch(statements);
    } else if(action==='indexing_save'){
      const url=clean(body.url,1000),status=yn(body.indexedStatus);if(!url)return json({error:'URL required'},400);await db.prepare('UPDATE seo_indexing_status SET indexed_status=?,google_canonical=?,last_checked=?,notes=?,checked_by=?,updated_at=? WHERE url=?').bind(status,clean(body.googleCanonical,1000)||null,clean(body.date,10)||null,clean(body.notes),actor.email,now,url).run();
    } else if(action==='geo_add'){
      const platform=clean(body.platform,30),prompt=clean(body.prompt,2000);if(!['Google AI','ChatGPT','Bing/Copilot'].includes(platform)||!prompt)return json({error:'Platform and prompt are required'},400);const source=platform==='ChatGPT'?'MANUAL CHATGPT TEST':platform==='Google AI'?'MANUAL GOOGLE AI TEST':'MANUAL BING TEST';await db.prepare('INSERT INTO seo_geo_tests (id,platform,checked_date,prompt,keyword,mentioned,cited,cited_url,correct_description,position_value,competitors,notes,checked_by,source_type,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,platform,clean(body.date,10),prompt,clean(body.keyword,300)||null,yn(body.mentioned),yn(body.cited),clean(body.citedUrl,1000)||null,yn(body.correctDescription),num(body.position),clean(body.competitors,2000)||null,clean(body.notes),actor.email,source,now).run();
    } else if(action==='backlink_add'){
      const domain=clean(body.domain,300),sourceUrl=clean(body.sourceUrl,1000),targetUrl=clean(body.targetUrl,1000);if(!domain||!sourceUrl||!targetUrl)return json({error:'Domain, source URL, and target URL are required'},400);await db.prepare("INSERT INTO seo_backlinks (id,referring_domain,source_url,target_url,first_discovered,link_type,authority_notes,industry,status,notes,checked_by,source_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?, 'MANUAL BACKLINK ENTRY',?,?)").bind(id,domain,sourceUrl,targetUrl,clean(body.date,10),['Follow','NoFollow','Unknown'].includes(body.linkType)?body.linkType:'Unknown',clean(body.authorityNotes)||null,clean(body.industry,200)||null,['Active','Lost','Pending','Outreach','Rejected'].includes(body.status)?body.status:'Active',clean(body.notes),actor.email,now,now).run();
    } else if(action==='profile_add'){
      const platform=clean(body.platform,200),profileUrl=clean(body.profileUrl,1000);if(!platform||!profileUrl)return json({error:'Platform and profile URL are required'},400);await db.prepare('INSERT INTO seo_authority_profiles (id,platform,profile_url,verified_status,backlink_status,created_date,status,notes,checked_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,platform,profileUrl,yn(body.verified),yn(body.backlink),clean(body.date,10)||null,clean(body.status,100)||null,clean(body.notes),actor.email,now,now).run();
    } else if(action==='task_save'){
      const taskId=clean(body.id,100),status=['Pending','Complete','Skipped'].includes(body.status)?body.status:'Pending';if(!taskId)return json({error:'Task required'},400);await db.prepare('UPDATE seo_manual_tasks SET status=?,checked_date=?,result=?,notes=?,assigned_to=?,updated_at=? WHERE id=?').bind(status,clean(body.date,10)||null,clean(body.result),clean(body.notes),actor.email,now,taskId).run();
    } else return json({error:'Unsupported action'},400);
    await audit(actor.id,`seo_geo_${action}`,{recordId:String(body.id||id)});return json({ok:true});
  }catch(error){return json({error:error instanceof Error?error.message:'Unable to save record'},400)}
}
