import type { Locale } from '@/lib/i18n';

export type IndustryKey =
  | 'wholesale'
  | 'hvac'
  | 'construction'
  | 'manufacturing'
  | 'restaurant'
  | 'retail'
  | 'professional'
  | 'other';
type Localized = Record<Locale, string>;
type Opportunity = { id: string; label: Localized; solution: Localized };
type IndustryConfig = {
  label: Localized;
  hero: Localized;
  image: string;
  imageAlt: Localized;
  tools: Localized[];
  opportunities: Opportunity[];
  roadmap: Array<{ title: Localized; item: Localized }>;
  resources: Array<{ href: string; label: Localized }>;
};
const l = (en: string, cn: string, tw: string, es: string): Localized => ({
  en,
  'zh-cn': cn,
  'zh-tw': tw,
  es,
});
const resource = (slug: string, labels: Localized) => ({
  href: `/resources/${slug}`,
  label: labels,
});
const coreResources = [
  resource('private-ai', l('Private AI for company knowledge', '企业知识私有 AI', '企業知識私有 AI', 'IA privada para conocimiento empresarial')),
  resource('odoo-erp', l('Odoo ERP operating guide', 'Odoo ERP 运营指南', 'Odoo ERP 營運指南', 'Guía operativa de Odoo ERP')),
  resource('ai-erp', l('Connecting AI and ERP', '连接 AI 与 ERP', '連接 AI 與 ERP', 'Conectar IA y ERP')),
];
const make = (
  label: Localized,
  hero: Localized,
  image: string,
  imageAlt: Localized,
  tools: Localized[],
  opportunities: Opportunity[],
  roadmap: IndustryConfig['roadmap'],
  industrySlug?: string,
): IndustryConfig => ({
  label,
  hero,
  image,
  imageAlt,
  tools,
  opportunities,
  roadmap,
  resources: industrySlug
    ? [resource(`industries/${industrySlug}`, label), ...coreResources]
    : coreResources,
});
const op = (id: string, label: Localized, solution: Localized): Opportunity => ({ id, label, solution });
const phase = (n: number, item: Localized) => ({
  title: l(`Phase ${n}`, `第 ${n} 阶段`, `第 ${n} 階段`, `Fase ${n}`),
  item,
});

export const industryConfig: Record<IndustryKey, IndustryConfig> = {
  restaurant: make(
    l('Restaurant','餐厅','餐廳','Restaurante'),
    l('Improve food cost, purchasing, inventory, kitchen workflow, training, and management visibility.','改善食品成本、采购、库存、厨房流程、培训和管理可视性。','改善食品成本、採購、庫存、廚房流程、培訓和管理可視性。','Mejore costos, compras, inventario, cocina, capacitación y visibilidad.'),
    '/restaurants/management-ai.png',
    l('Restaurant owner and kitchen manager reviewing operating information','餐厅经营者与厨房经理查看运营信息','餐廳經營者與廚房經理查看營運資訊','Propietario y gerente revisando operaciones'),
    [l('Restaurant AI & ERP Readiness Assessment','餐厅 AI 与 ERP 准备度评估','餐廳 AI 與 ERP 準備度評估','Evaluación de IA y ERP para restaurantes'),l('Food Cost & Recipe Review','食品与食谱成本审核','食品與食譜成本審核','Revisión de costos y recetas'),l('Inventory & Purchasing Assessment','库存与采购评估','庫存與採購評估','Evaluación de inventario y compras'),l('Waste Opportunity Finder','浪费机会分析','浪費機會分析','Análisis de desperdicio'),l('Private Restaurant Knowledge AI','餐厅私有知识 AI','餐廳私有知識 AI','IA privada para restaurantes'),l('Restaurant ROI Calculator','餐厅投资回报计算器','餐廳投資回報計算器','Calculadora ROI para restaurantes')],
    [op('food-cost',l('Recipe and food cost visibility is incomplete','食谱与食品成本可视性不足','食譜與食品成本可視性不足','La visibilidad de costos es incompleta'),l('Recipe and food-cost controls','食谱与食品成本控制','食譜與食品成本控制','Controles de recetas y costos')),op('waste',l('Waste and overproduction are not measured','浪费与过量生产未被衡量','浪費與過量生產未被衡量','No se mide el desperdicio'),l('Waste and demand analysis','浪费与需求分析','浪費與需求分析','Análisis de desperdicio y demanda')),op('buying',l('Vendor price changes are difficult to see','供应商价格变化难以发现','供應商價格變化難以發現','Es difícil ver cambios de proveedores'),l('Vendor price and purchasing history','供应商价格与采购历史','供應商價格與採購歷史','Historial de precios y compras')),op('inventory',l('Ingredient inventory is unreliable','食材库存不可靠','食材庫存不可靠','El inventario de ingredientes no es confiable'),l('Connected ingredient inventory','互联食材库存','互聯食材庫存','Inventario conectado')),op('training',l('Training depends on managers repeating instructions','培训依赖经理重复指导','培訓依賴經理重複指導','La capacitación depende de gerentes'),l('Private recipe and SOP assistant','私有食谱与 SOP 助手','私有食譜與 SOP 助手','Asistente privado de recetas')),op('reporting',l('Management reporting is delayed','管理报告延迟','管理報告延遲','Los informes se retrasan'),l('Restaurant management dashboard','餐厅管理仪表板','餐廳管理儀表板','Panel de gestión del restaurante'))],
    [phase(1,l('Standardize recipes, vendors, ingredients, and operating definitions','标准化食谱、供应商、食材和运营定义','標準化食譜、供應商、食材和營運定義','Estandarizar recetas, proveedores e ingredientes')),phase(2,l('Connect POS summaries, purchasing, inventory, and accounting','连接 POS 汇总、采购、库存和会计','連接 POS 彙總、採購、庫存和會計','Conectar POS, compras, inventario y contabilidad')),phase(3,l('Deploy a private recipe, SOP, and training assistant','部署私有食谱、SOP 和培训助手','部署私有食譜、SOP 和培訓助手','Implementar asistente privado de recetas y SOP')),phase(4,l('Add demand forecasting, anomaly alerts, and management intelligence','增加需求预测、异常警报与管理智能','增加需求預測、異常警報與管理智慧','Añadir pronóstico, alertas e inteligencia'))],
    'restaurants',
  ),
  wholesale: make(
    l('Wholesale Distribution', '批发与分销', '批發與分銷', 'Distribución mayorista'),
    l('See where inventory, purchasing, sales, and AI automation can improve your operation.', '了解库存、采购、销售与 AI 自动化如何改善您的运营。', '了解庫存、採購、銷售與 AI 自動化如何改善您的營運。', 'Vea cómo inventario, compras, ventas y automatización con IA pueden mejorar su operación.'),
    '/industries/wholesale-distribution.webp',
    l('Warehouse team coordinating inventory and fulfillment', '仓库团队协调库存与履约', '倉庫團隊協調庫存與履約', 'Equipo de almacén coordinando inventario y entregas'),
    [l('Inventory Efficiency Assessment','库存效率评估','庫存效率評估','Evaluación de eficiencia de inventario'),l('AI & ERP Readiness Assessment','AI 与 ERP 准备度评估','AI 與 ERP 準備度評估','Evaluación de preparación IA y ERP'),l('Customer Profitability Analysis','客户盈利分析','客戶獲利分析','Análisis de rentabilidad por cliente'),l('Purchasing Automation Finder','采购自动化查找器','採購自動化查找器','Buscador de automatización de compras'),l('Warehouse SOP AI','仓库 SOP AI','倉庫 SOP AI','IA para procedimientos de almacén'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],
    [op('stock',l('Inventory numbers do not always match','库存数量经常不一致','庫存數量經常不一致','Las cantidades de inventario no siempre coinciden'),l('Inventory accuracy workflow','库存准确性流程','庫存準確性流程','Flujo de exactitud de inventario')),op('pricing',l('Customer-specific pricing is difficult to manage','客户专属价格难以管理','客戶專屬價格難以管理','Es difícil gestionar precios por cliente'),l('Sales and pricing controls','销售与定价控制','銷售與定價控制','Controles de ventas y precios')),op('buying',l('Purchasing is reactive','采购依赖临时反应','採購依賴臨時反應','Las compras son reactivas'),l('Purchase and replenishment planning','采购与补货规划','採購與補貨規劃','Planificación de compras y reposición')),op('slow',l('Slow-moving inventory is hard to identify','呆滞库存难以识别','呆滯庫存難以識別','Es difícil identificar inventario lento'),l('Inventory aging reporting','库存库龄报告','庫存庫齡報告','Informes de antigüedad de inventario')),op('sop',l('Warehouse procedures are inconsistent','仓库程序不一致','倉庫程序不一致','Los procedimientos de almacén son inconsistentes'),l('Private warehouse SOP assistant','私有仓库 SOP 助手','私有倉庫 SOP 助手','Asistente privado de procedimientos')),op('margin',l('Profitability by customer or product is unclear','客户或产品盈利不清晰','客戶或產品獲利不清晰','La rentabilidad por cliente o producto no está clara'),l('Customer and product margin analysis','客户与产品利润分析','客戶與產品利潤分析','Análisis de margen por cliente y producto'))],
    [phase(1,l('Clean inventory and master data','清理库存与主数据','清理庫存與主資料','Limpiar inventario y datos maestros')),phase(2,l('Establish Sales, Purchase, and Inventory ERP','建立销售、采购与库存 ERP','建立銷售、採購與庫存 ERP','Establecer ERP de Ventas, Compras e Inventario')),phase(3,l('Deploy a private warehouse SOP assistant','部署私有仓库 SOP 助手','部署私有倉庫 SOP 助手','Implementar un asistente privado de procedimientos')),phase(4,l('Add purchasing automation and management reporting','增加采购自动化与管理报告','增加採購自動化與管理報告','Añadir automatización de compras e informes'))],
    'wholesale-distribution',
  ),
  hvac: make(
    l('HVAC / Field Service','暖通空调 / 现场服务','暖通空調 / 現場服務','HVAC / Servicio de campo'),
    l('Manage service workflows, technician knowledge, memberships, and customer follow-up more effectively.','更有效地管理服务流程、技术员知识、会员计划与客户跟进。','更有效地管理服務流程、技術員知識、會員計劃與客戶跟進。','Gestione mejor los servicios, el conocimiento técnico, las membresías y el seguimiento.'),
    '/industries/hvac-field-service.webp',l('HVAC technician servicing commercial equipment','暖通技术员维护商用设备','暖通技術員維護商用設備','Técnico HVAC atendiendo equipo comercial'),
    [l('HVAC Operations Assessment','暖通运营评估','暖通營運評估','Evaluación de operaciones HVAC'),l('Technician Productivity Assessment','技术员生产力评估','技術員生產力評估','Evaluación de productividad técnica'),l('Maintenance Membership Calculator','维护会员计划计算器','維護會員計劃計算器','Calculadora de membresías'),l('Field Service ERP Planner','现场服务 ERP 规划器','現場服務 ERP 規劃器','Planificador ERP de servicio'),l('Technician SOP AI','技术员 SOP AI','技術員 SOP AI','IA de procedimientos técnicos'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],
    [op('dispatch',l('Dispatching is manual','调度依赖人工','調度依賴人工','El despacho es manual'),l('Field service scheduling','现场服务排程','現場服務排程','Programación de servicio')),op('history',l('Technicians call for service history','技术员需致电查询服务历史','技術員需致電查詢服務歷史','Los técnicos llaman por el historial'),l('Mobile equipment history','移动设备历史','行動設備歷史','Historial móvil de equipos')),op('membership',l('Maintenance memberships are tracked manually','维护会员计划手工跟踪','維護會員計劃手工追蹤','Las membresías se controlan manualmente'),l('Subscription and membership workflow','订阅与会员流程','訂閱與會員流程','Flujo de suscripciones')),op('training',l('Technician training takes too long','技术员培训耗时过长','技術員培訓耗時過長','La capacitación tarda demasiado'),l('Private technician knowledge AI','私有技术员知识 AI','私有技術員知識 AI','IA privada de conocimiento técnico')),op('parts',l('Parts availability is unclear','零件可用性不清晰','零件可用性不清晰','La disponibilidad de repuestos no está clara'),l('Parts inventory visibility','零件库存可视化','零件庫存可視化','Visibilidad de inventario de repuestos')),op('followup',l('Customer follow-up is inconsistent','客户跟进不一致','客戶跟進不一致','El seguimiento al cliente es inconsistente'),l('CRM follow-up automation','CRM 跟进自动化','CRM 跟進自動化','Automatización de seguimiento CRM'))],
    [phase(1,l('Structure customer, equipment, and service data','整理客户、设备与服务数据','整理客戶、設備與服務資料','Estructurar datos de clientes, equipos y servicios')),phase(2,l('Implement CRM, Field Service, and memberships','实施 CRM、现场服务与会员计划','實施 CRM、現場服務與會員計劃','Implementar CRM, servicio y membresías')),phase(3,l('Deploy a technician knowledge assistant','部署技术员知识助手','部署技術員知識助手','Implementar un asistente técnico')),phase(4,l('Automate service follow-up and reporting','自动化服务跟进与报告','自動化服務跟進與報告','Automatizar seguimiento e informes'))],
    'hvac-field-service',
  ),
  construction: make(l('Construction','建筑工程','建築工程','Construcción'),l('Identify opportunities across project management, job costing, documents, and field operations.','发现项目管理、工作成本、文档与现场运营中的机会。','發現專案管理、工作成本、文件與現場營運中的機會。','Identifique oportunidades en proyectos, costos, documentos y operaciones de campo.'),'/industries/construction.webp',l('Project manager reviewing an active job site','项目经理查看施工现场','專案經理查看施工現場','Gerente revisando una obra'),[l('Construction Workflow Assessment','建筑流程评估','建築流程評估','Evaluación de procesos de construcción'),l('Job Costing Readiness','项目成本准备度','專案成本準備度','Preparación de costos de obra'),l('Project Process Analyzer','项目流程分析器','專案流程分析器','Analizador de procesos de proyecto'),l('Document / SOP AI','文档 / SOP AI','文件 / SOP AI','IA para documentos'),l('Change Order Review','变更单审核','變更單審核','Revisión de órdenes de cambio'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],[op('changes',l('Change orders are difficult to track','变更单难以跟踪','變更單難以追蹤','Es difícil controlar órdenes de cambio'),l('Change order workflow','变更单流程','變更單流程','Flujo de órdenes de cambio')),op('cost',l('Job costing is delayed','项目成本核算延迟','專案成本核算延遲','El costo de obra se retrasa'),l('Current job-cost reporting','实时项目成本报告','即時專案成本報告','Informes actuales de costos')),op('docs',l('Project documents are scattered','项目文档分散','專案文件分散','Los documentos están dispersos'),l('Controlled project document search','受控项目文档搜索','受控專案文件搜尋','Búsqueda controlada de documentos')),op('subs',l('Subcontractor communication is inconsistent','分包商沟通不一致','分包商溝通不一致','La comunicación con subcontratistas es inconsistente'),l('Project communication workflow','项目沟通流程','專案溝通流程','Flujo de comunicación')),op('materials',l('Material purchasing is hard to control','材料采购难以控制','材料採購難以控制','Es difícil controlar compras de materiales'),l('Project purchasing controls','项目采购控制','專案採購控制','Controles de compras por proyecto')),op('status',l('Project status reporting is manual','项目状态报告依赖人工','專案狀態報告依賴人工','Los informes de estado son manuales'),l('Project status dashboard','项目状态仪表板','專案狀態儀表板','Panel de estado de proyectos'))],[phase(1,l('Standardize project, vendor, and cost data','标准化项目、供应商与成本数据','標準化專案、供應商與成本資料','Estandarizar datos de proyectos y costos')),phase(2,l('Connect projects, purchasing, and job costing','连接项目、采购与成本核算','連接專案、採購與成本核算','Conectar proyectos, compras y costos')),phase(3,l('Deploy controlled document and SOP AI','部署受控文档与 SOP AI','部署受控文件與 SOP AI','Implementar IA controlada para documentos')),phase(4,l('Automate change orders and project reporting','自动化变更单与项目报告','自動化變更單與專案報告','Automatizar cambios e informes'))],'construction'),
  manufacturing: make(l('Manufacturing','制造业','製造業','Manufactura'),l('Improve production visibility, inventory, purchasing, procedures, and employee knowledge.','改善生产可视性、库存、采购、程序与员工知识。','改善生產可視性、庫存、採購、程序與員工知識。','Mejore producción, inventario, compras, procedimientos y conocimiento.'),'/industries/manufacturing.webp',l('Production team on a modern manufacturing floor','现代制造车间生产团队','現代製造車間生產團隊','Equipo en una planta moderna'),[l('Manufacturing Readiness Assessment','制造准备度评估','製造準備度評估','Evaluación de manufactura'),l('Production Workflow Analyzer','生产流程分析器','生產流程分析器','Analizador de producción'),l('Inventory & Purchasing Assessment','库存与采购评估','庫存與採購評估','Evaluación de inventario y compras'),l('SOP / Quality AI','SOP / 质量 AI','SOP / 品質 AI','IA para calidad'),l('BOM / Production ERP Planner','BOM / 生产 ERP 规划器','BOM / 生產 ERP 規劃器','Planificador ERP de producción'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],[op('materials',l('Material availability interrupts production','材料短缺影响生产','材料短缺影響生產','La falta de materiales interrumpe producción'),l('Material requirements planning','物料需求规划','物料需求規劃','Planificación de materiales')),op('orders',l('Work orders lack current status','工单状态不及时','工單狀態不及時','Las órdenes no tienen estado actual'),l('Production work-order visibility','生产工单可视化','生產工單可視化','Visibilidad de órdenes')),op('bom',l('BOM revisions are difficult to control','BOM 版本难以控制','BOM 版本難以控制','Es difícil controlar revisiones BOM'),l('BOM revision control','BOM 版本控制','BOM 版本控制','Control de revisiones BOM')),op('quality',l('Quality procedures are hard to find','质量程序难以查找','品質程序難以查找','Los procedimientos de calidad son difíciles de encontrar'),l('Private quality SOP AI','私有质量 SOP AI','私有品質 SOP AI','IA privada para calidad')),op('buying',l('Purchasing reacts to shortages','采购被短缺推动','採購被短缺推動','Compras reacciona a faltantes'),l('Demand-based purchasing','需求驱动采购','需求驅動採購','Compras basadas en demanda')),op('reports',l('Production reporting is manual','生产报告依赖人工','生產報告依賴人工','Los informes de producción son manuales'),l('Production reporting workflow','生产报告流程','生產報告流程','Flujo de informes de producción'))],[phase(1,l('Clean products, BOMs, and inventory data','清理产品、BOM 与库存数据','清理產品、BOM 與庫存資料','Limpiar productos, BOM e inventario')),phase(2,l('Implement inventory, MRP, and work orders','实施库存、MRP 与工单','實施庫存、MRP 與工單','Implementar inventario, MRP y órdenes')),phase(3,l('Deploy quality and SOP knowledge AI','部署质量与 SOP 知识 AI','部署品質與 SOP 知識 AI','Implementar IA de calidad y SOP')),phase(4,l('Automate exceptions and production reporting','自动化异常与生产报告','自動化異常與生產報告','Automatizar excepciones e informes'))],'manufacturing'),
  retail: make(l('Retail','零售','零售','Comercio minorista'),l('Connect sales, inventory, customers, purchasing, and store operations.','连接销售、库存、客户、采购与门店运营。','連接銷售、庫存、客戶、採購與門店營運。','Conecte ventas, inventario, clientes, compras y tiendas.'),'/industries/retail.webp',l('Retail team coordinating merchandise and customers','零售团队协调商品与客户','零售團隊協調商品與客戶','Equipo minorista coordinando productos y clientes'),[l('Retail Operations Assessment','零售运营评估','零售營運評估','Evaluación de operaciones minoristas'),l('POS + Inventory Review','POS + 库存审核','POS + 庫存審核','Revisión de POS e inventario'),l('Customer Follow-Up Automation','客户跟进自动化','客戶跟進自動化','Automatización de seguimiento'),l('Multi-location Readiness','多门店准备度','多門店準備度','Preparación multitienda'),l('Purchasing Analyzer','采购分析器','採購分析器','Analizador de compras'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],[op('stock',l('Store inventory is not reliable','门店库存不可靠','門店庫存不可靠','El inventario de tienda no es confiable'),l('POS and inventory integration','POS 与库存集成','POS 與庫存整合','Integración POS e inventario')),op('locations',l('Stock transfers are hard to track','库存调拨难以跟踪','庫存調撥難以追蹤','Es difícil controlar transferencias'),l('Multi-location stock control','多门店库存控制','多門店庫存控制','Control de inventario multitienda')),op('returns',l('Returns create disconnected records','退货产生断开的记录','退貨產生斷開的記錄','Las devoluciones crean registros separados'),l('Connected returns workflow','集成退货流程','整合退貨流程','Flujo conectado de devoluciones')),op('followup',l('Customer follow-up is inconsistent','客户跟进不一致','客戶跟進不一致','El seguimiento es inconsistente'),l('Customer follow-up automation','客户跟进自动化','客戶跟進自動化','Automatización de seguimiento')),op('buying',l('Reordering is reactive','补货依赖临时反应','補貨依賴臨時反應','La reposición es reactiva'),l('Demand-based replenishment','需求驱动补货','需求驅動補貨','Reposición basada en demanda')),op('reports',l('Store reporting requires spreadsheets','门店报告依赖表格','門店報告依賴表格','Los informes requieren hojas de cálculo'),l('Multi-store reporting','多门店报告','多門店報告','Informes multitienda'))],[phase(1,l('Clean product, customer, and store data','清理产品、客户与门店数据','清理產品、客戶與門店資料','Limpiar productos, clientes y tiendas')),phase(2,l('Connect POS, inventory, purchasing, and returns','连接 POS、库存、采购与退货','連接 POS、庫存、採購與退貨','Conectar POS, inventario, compras y devoluciones')),phase(3,l('Deploy store procedure and product knowledge AI','部署门店程序与产品知识 AI','部署門店程序與產品知識 AI','Implementar IA de procedimientos y productos')),phase(4,l('Automate replenishment and customer follow-up','自动化补货与客户跟进','自動化補貨與客戶跟進','Automatizar reposición y seguimiento'))],'retail'),
  professional: make(l('Professional Services','专业服务','專業服務','Servicios profesionales'),l('Improve client management, internal knowledge, workflows, reporting, and team productivity.','改善客户管理、内部知识、流程、报告与团队生产力。','改善客戶管理、內部知識、流程、報告與團隊生產力。','Mejore clientes, conocimiento, flujos, informes y productividad.'),'/industries/service-companies.webp',l('Professional services team collaborating with a client','专业服务团队与客户协作','專業服務團隊與客戶協作','Equipo profesional colaborando con un cliente'),[l('Service Operations Assessment','服务运营评估','服務營運評估','Evaluación de operaciones'),l('Client Workflow Review','客户流程审核','客戶流程審核','Revisión de flujo de clientes'),l('Project Profitability Analysis','项目盈利分析','專案獲利分析','Análisis de rentabilidad'),l('Document Knowledge AI','文档知识 AI','文件知識 AI','IA de conocimiento documental'),l('Billing Process Analyzer','计费流程分析器','計費流程分析器','Analizador de facturación'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],[op('handoff',l('Client handoffs are inconsistent','客户交接不一致','客戶交接不一致','Los traspasos de clientes son inconsistentes'),l('Client delivery workflow','客户交付流程','客戶交付流程','Flujo de entrega al cliente')),op('scope',l('Project scope is difficult to track','项目范围难以跟踪','專案範圍難以追蹤','Es difícil controlar el alcance'),l('Project scope controls','项目范围控制','專案範圍控制','Controles de alcance')),op('time',l('Time and billing records are disconnected','工时与计费记录断开','工時與計費記錄斷開','Tiempo y facturación están desconectados'),l('Time-to-billing workflow','工时到计费流程','工時到計費流程','Flujo de tiempo a facturación')),op('docs',l('Team knowledge is scattered','团队知识分散','團隊知識分散','El conocimiento está disperso'),l('Private document knowledge AI','私有文档知识 AI','私有文件知識 AI','IA privada de documentos')),op('capacity',l('Resource capacity is hard to see','资源容量难以查看','資源容量難以查看','Es difícil ver la capacidad'),l('Resource planning','资源规划','資源規劃','Planificación de recursos')),op('reports',l('Client reporting is manual','客户报告依赖人工','客戶報告依賴人工','Los informes de clientes son manuales'),l('Client reporting workflow','客户报告流程','客戶報告流程','Flujo de informes'))],[phase(1,l('Standardize client, project, and service data','标准化客户、项目与服务数据','標準化客戶、專案與服務資料','Estandarizar datos de clientes y proyectos')),phase(2,l('Connect CRM, projects, time, and billing','连接 CRM、项目、工时与计费','連接 CRM、專案、工時與計費','Conectar CRM, proyectos, tiempo y facturación')),phase(3,l('Deploy a private team knowledge assistant','部署私有团队知识助手','部署私有團隊知識助手','Implementar un asistente privado de conocimiento')),phase(4,l('Automate reporting and recurring workflows','自动化报告与周期流程','自動化報告與週期流程','Automatizar informes y flujos recurrentes'))],'professional-services'),
  other: make(l('Other','其他','其他','Otro'),l('Explore practical opportunities across connected operations, private knowledge, and responsible automation.','探索互联运营、私有知识与负责任自动化中的实际机会。','探索互聯營運、私有知識與負責任自動化中的實際機會。','Explore oportunidades en operaciones conectadas, conocimiento privado y automatización responsable.'),'/industries/service-companies.webp',l('Business team reviewing operations','企业团队审视运营','企業團隊檢視營運','Equipo revisando operaciones'),[l('AI & ERP Readiness Assessment','AI 与 ERP 准备度评估','AI 與 ERP 準備度評估','Evaluación IA y ERP'),l('Opportunity Finder','机会查找器','機會查找器','Buscador de oportunidades'),l('Workflow Review','流程审核','流程審核','Revisión de procesos'),l('Private Knowledge AI','私有知识 AI','私有知識 AI','IA privada'),l('ERP Foundation Planner','ERP 基础规划器','ERP 基礎規劃器','Planificador ERP'),l('ROI Calculator','投资回报计算器','投資回報計算器','Calculadora de ROI')],[op('reentry',l('Data is entered in multiple systems','数据重复录入多个系统','資料重複輸入多個系統','Los datos se capturan en varios sistemas'),l('Connected workflow automation','互联流程自动化','互聯流程自動化','Automatización conectada')),op('sops',l('Procedures are difficult to find','程序难以查找','程序難以查找','Los procedimientos son difíciles de encontrar'),l('Private SOP search','私有 SOP 搜索','私有 SOP 搜尋','Búsqueda privada de procedimientos')),op('reports',l('Reporting requires spreadsheets','报告依赖电子表格','報告依賴試算表','Los informes requieren hojas de cálculo'),l('Connected management reporting','互联管理报告','互聯管理報告','Informes de gestión conectados'))],[phase(1,l('Organize data and process ownership','整理数据与流程责任','整理資料與流程責任','Organizar datos y responsables')),phase(2,l('Establish a connected ERP foundation','建立互联 ERP 基础','建立互聯 ERP 基礎','Establecer una base ERP conectada')),phase(3,l('Pilot private company knowledge AI','试点私有企业知识 AI','試行私有企業知識 AI','Probar IA privada de conocimiento')),phase(4,l('Add controlled automation and reporting','增加受控自动化与报告','增加受控自動化與報告','Añadir automatización e informes'))]),
};

export const industryChoices: IndustryKey[] = ['wholesale','hvac','construction','restaurant','manufacturing','retail','professional','other'];
export function industryKey(value?: string): IndustryKey {
  const text = String(value ?? '').toLowerCase();
  if (text.includes('wholesale') || text.includes('distribution') || text.includes('批发') || text.includes('批發')) return 'wholesale';
  if (text.includes('hvac') || text.includes('field service') || text.includes('暖通')) return 'hvac';
  if (text.includes('construction') || text.includes('建筑') || text.includes('建築')) return 'construction';
  if (text.includes('manufactur') || text.includes('制造') || text.includes('製造')) return 'manufacturing';
  if (text.includes('restaurant') || text.includes('餐厅') || text.includes('餐廳') || text.includes('buffet')) return 'restaurant';
  if (text.includes('retail') || text.includes('零售')) return 'retail';
  if (text.includes('professional') || text.includes('service compan') || text.includes('专业服务') || text.includes('專業服務')) return 'professional';
  return 'other';
}
export const localized = (value: Localized, locale: Locale) => value[locale] || value.en;
