import type { Locale } from '@/lib/i18n';

export type ResourceCopy = {
  title: string;
  description: string;
  answer: string;
  operations: string;
  example: string;
  limits: string;
  questions: [string, string][];
};

export type ResourceEntry = {
  slug: string;
  pillar: string;
  audience: string;
  related: { label: string; href: string }[];
  copy: Record<Locale, ResourceCopy>;
};

const relatedCore = [
  { label: 'Private AI solutions', href: '/ai-solutions' },
  { label: 'Odoo ERP solutions', href: '/erp-solutions' },
  { label: 'AI + ERP integration', href: '/ai-erp' },
];

export const resourceEntries: ResourceEntry[] = [
  {
    slug: 'private-ai', pillar: 'Private AI', audience: 'Owners, operations leaders, and IT decision-makers', related: [{ label: 'Private AI solutions', href: '/ai-solutions' }, { label: 'Private AI equipment', href: '/equipment' }, { label: 'Private AI pricing', href: '/pricing' }],
    copy: {
      en: { title: 'What is private AI for a business?', description: 'A practical guide to private AI, company knowledge search, permissions, local hardware, cost drivers, and implementation readiness.', answer: 'Private AI is an AI system configured to work with approved company documents, data, and business systems under controlled access rules. Privacy depends on where models run, where information is stored, which external services are used, and how permissions are enforced. It can help employees search SOPs, manuals, PDFs, spreadsheets, and internal knowledge without giving every user access to everything.', operations: 'A useful implementation starts with a defined business question, not a model. The company selects authoritative documents, assigns owners, defines department permissions, and tests answers against real employee questions. Local hardware can keep inference and indexed data under company control; controlled cloud infrastructure may be more practical when access, scale, or support requirements outweigh local operation.', example: 'A warehouse employee could ask, “What is our approved process for receiving damaged product?” The system retrieves the current receiving SOP, cites the relevant section, and answers within the employee’s permissions. It should not invent a return authorization or approve a vendor claim. That action remains in the ERP workflow with the responsible employee.', limits: 'AI responses can be wrong, outdated documents produce outdated answers, and access rules require careful testing. Hardware needs vary by model size, concurrent users, response speed, and document volume. Companies should prepare document owners, a permission model, representative questions, and an escalation process before launch.', questions: [['Can private AI search Word files and PDFs?', 'Yes, when supported files are extracted, indexed, permissioned, and kept current. Scanned files may need optical character recognition and quality review.'], ['Should every company host AI locally?', 'No. Local hosting can improve control, but it also creates responsibility for hardware, security, backups, updates, and support.']] },
      'zh-cn': { title: '企业私有 AI 是什么？', description: '面向企业管理者的私有 AI 指南，涵盖知识检索、权限、本地硬件、成本因素与实施准备。', answer: '私有 AI 是按照受控访问规则使用企业批准的文档、数据和业务系统的 AI。实际隐私程度取决于模型运行位置、信息存储位置、使用哪些外部服务以及权限如何执行。它可以帮助员工检索 SOP、手册、PDF、表格和内部知识，但不会让所有人看到全部资料。', operations: '有效的实施应从明确的业务问题开始，而不是先选模型。企业需要确定权威资料、指定内容负责人、设置部门权限，并用真实员工问题测试答案。本地硬件可让推理和索引数据留在企业控制范围内；当规模、访问或支持更重要时，受控云环境可能更合适。', example: '仓库员工可以询问：“收到供应商破损货物时，公司批准的流程是什么？”系统检索最新收货 SOP、引用相关段落，并在员工权限内回答。它不应虚构退货授权或批准供应商索赔；相关操作仍由负责人在 ERP 流程中完成。', limits: 'AI 可能回答错误，过期资料会产生过时答案，权限规则也必须认真测试。硬件需求取决于模型大小、并发用户、响应速度和文档数量。上线前应明确资料负责人、权限模型、代表性问题和升级处理流程。', questions: [['私有 AI 能检索 Word 和 PDF 吗？', '可以，但文件必须完成提取、索引、权限设置并保持更新。扫描文件可能还需要文字识别和质量检查。'], ['每家公司都应该本地部署 AI 吗？', '不一定。本地部署提高控制力，但企业也要负责硬件、安全、备份、更新和支持。']] },
      'zh-tw': { title: '企業私有 AI 是什麼？', description: '面向企業管理者的私有 AI 指南，涵蓋知識檢索、權限、本地硬體、成本因素與實施準備。', answer: '私有 AI 是按照受控存取規則使用企業核准文件、資料和業務系統的 AI。實際私隱程度取決於模型運行位置、資訊儲存位置、使用哪些外部服務及權限如何執行。它可協助員工檢索 SOP、手冊、PDF、試算表及內部知識，但不會讓所有人看到全部資料。', operations: '有效實施應從明確的業務問題開始，而不是先選模型。企業需要確定權威資料、指定內容負責人、設定部門權限，並用真實員工問題測試答案。本地硬體可讓推理和索引資料留在企業控制範圍；當規模、存取或支援更重要時，受控雲端環境可能更合適。', example: '倉庫員工可以詢問：「收到供應商破損貨物時，公司核准的流程是什麼？」系統檢索最新收貨 SOP、引用相關段落，並在員工權限內回答。它不應虛構退貨授權或批准供應商索賠；相關操作仍由負責人在 ERP 流程中完成。', limits: 'AI 可能回答錯誤，過期資料會產生過時答案，權限規則亦必須認真測試。硬體需求取決於模型大小、同時使用人數、回應速度及文件數量。上線前應明確資料負責人、權限模型、代表性問題和升級處理流程。', questions: [['私有 AI 能檢索 Word 和 PDF 嗎？', '可以，但文件必須完成擷取、索引、權限設定並保持更新。掃描文件可能還需要文字識別和品質檢查。'], ['每家公司都應該本地部署 AI 嗎？', '不一定。本地部署提高控制力，但企業亦要負責硬體、安全、備份、更新和支援。']] },
      es: { title: '¿Qué es la IA privada para una empresa?', description: 'Guía práctica sobre IA privada, búsqueda de conocimiento, permisos, hardware local, costos y preparación.', answer: 'La IA privada es un sistema configurado para trabajar con documentos, datos y sistemas empresariales aprobados bajo reglas de acceso controladas. La privacidad depende de dónde se ejecutan los modelos, dónde se almacena la información, qué servicios externos se usan y cómo se aplican los permisos. Puede buscar procedimientos, manuales, PDF, hojas de cálculo y conocimiento interno sin dar acceso total a cada usuario.', operations: 'Una implementación útil empieza con una pregunta empresarial definida, no con un modelo. La empresa selecciona fuentes autorizadas, asigna responsables, define permisos por departamento y prueba respuestas con preguntas reales. El hardware local puede mantener la inferencia y los índices bajo control directo; una nube controlada puede ser más práctica cuando importan más la escala, el acceso o el soporte.', example: 'Un empleado de almacén podría preguntar: “¿Cuál es el proceso aprobado para recibir producto dañado?” El sistema recupera el procedimiento vigente, cita la sección y responde dentro de sus permisos. No debe inventar una autorización de devolución ni aprobar un reclamo; esa acción continúa en el ERP con la persona responsable.', limits: 'La IA puede equivocarse, los documentos desactualizados producen respuestas desactualizadas y los permisos requieren pruebas. El hardware depende del modelo, usuarios simultáneos, velocidad y volumen documental. Antes del lanzamiento se necesitan responsables de contenido, reglas de acceso, preguntas representativas y un proceso de escalamiento.', questions: [['¿Puede buscar archivos Word y PDF?', 'Sí, cuando los archivos se extraen, indexan, autorizan y mantienen. Los escaneos pueden requerir reconocimiento óptico y revisión.'], ['¿Toda empresa debe alojar IA localmente?', 'No. El alojamiento local mejora el control, pero también exige administrar hardware, seguridad, copias, actualizaciones y soporte.']] },
    },
  },
  {
    slug: 'odoo-erp', pillar: 'Odoo ERP', audience: 'Owners, controllers, sales, warehouse, and service managers', related: [{ label: 'ERP solutions', href: '/erp-solutions' }, { label: 'ERP pricing', href: '/pricing' }, { label: 'Odoo screenshots', href: '/erp-solutions#showcase' }],
    copy: {
      en: { title: 'What is Odoo ERP, and when does it fit?', description: 'A business guide to Odoo modules, Community versus Enterprise, implementation, migration, cost, and operating fit.', answer: 'Odoo is a modular ERP platform that can connect CRM, sales, purchasing, inventory, projects, field service, subscriptions, ecommerce, and other workflows around shared records. It fits businesses that have outgrown disconnected spreadsheets or single-purpose tools and are prepared to define how work should move between departments. Software selection alone does not create a working ERP; process design, migration, permissions, training, and support determine the result.', operations: 'Community can suit organizations with capable technical ownership and requirements covered by its available modules. Enterprise adds commercial features and vendor services that may reduce custom work. The right choice depends on needed applications, accounting approach, integrations, hosting, upgrade expectations, and who will maintain the system. Odoo can support inventory, purchasing, multiple warehouses, CRM, field service, memberships, and subscriptions when those processes are configured deliberately.', example: 'A wholesale order can reserve stock, create a delivery, expose a replenishment need, and carry customer-specific pricing without re-entering the same information in separate tools. Managers can review sales, available inventory, incoming purchases, and exceptions from the same operating record instead of reconciling spreadsheets after the fact.', limits: 'Odoo is not a shortcut around unclear processes or poor data. Implementations fail when scope expands without control, users are excluded from design, migration data is not cleaned, customizations are excessive, or training stops at launch. QuickBooks may remain appropriate for a small accounting-only need; replacement depends on financial requirements, controls, integrations, and the accounting team.', questions: [['How long does implementation take?', 'A focused first phase may take weeks; multi-company, manufacturing, complex integrations, or extensive migration can take months. Scope and decision speed matter more than module count alone.'], ['How much ongoing support is needed?', 'Support should cover user questions, monitoring, updates, access changes, integrations, and a controlled improvement backlog.']] },
      'zh-cn': { title: 'Odoo ERP 是什么，什么时候适合企业？', description: '从业务角度了解 Odoo 模块、社区版与企业版、实施、迁移、成本和适用条件。', answer: 'Odoo 是模块化 ERP 平台，可围绕共享记录连接 CRM、销售、采购、库存、项目、现场服务、订阅和电子商务等流程。它适合已经无法依靠零散表格或单一工具运营，并愿意明确跨部门工作流程的企业。只选择软件不会自动形成有效 ERP；流程设计、数据迁移、权限、培训和持续支持决定最终效果。', operations: '社区版可能适合拥有内部技术能力且现有模块能够满足需求的企业。企业版增加商业功能和厂商服务，可能减少定制工作。选择取决于所需应用、会计方式、集成、托管、升级要求和维护责任。通过认真配置，Odoo 可以管理库存、采购、多仓库、CRM、现场服务、会员和订阅。', example: '批发订单可以自动预留库存、创建发货任务、显示补货需求并应用客户专属价格，不必在多个工具中重复录入。管理者可从同一业务记录查看销售、可用库存、在途采购和异常，而不是事后拼接表格。', limits: 'Odoo 无法弥补模糊流程或低质量数据。范围失控、用户未参与设计、迁移数据未清理、过度定制或上线后停止培训，都会造成失败。对于只需要基础会计的小企业，QuickBooks 可能仍然合适；是否替换取决于财务要求、控制、集成和会计团队。', questions: [['实施需要多久？', '聚焦的第一阶段可能需要数周；多公司、制造、复杂集成或大量迁移通常需要数月。范围和决策速度比模块数量更重要。'], ['需要多少持续支持？', '支持应涵盖用户问题、监控、更新、权限变化、集成和受控的改进清单。']] },
      'zh-tw': { title: 'Odoo ERP 是什麼，什麼時候適合企業？', description: '從業務角度了解 Odoo 模組、社群版與企業版、實施、遷移、成本和適用條件。', answer: 'Odoo 是模組化 ERP 平台，可圍繞共享記錄連接 CRM、銷售、採購、庫存、項目、現場服務、訂閱和電子商務等流程。它適合已無法依靠零散試算表或單一工具營運，並願意明確跨部門工作流程的企業。只選擇軟體不會自動形成有效 ERP；流程設計、資料遷移、權限、培訓和持續支援決定最終效果。', operations: '社群版可能適合擁有內部技術能力且現有模組能滿足需求的企業。企業版增加商業功能和廠商服務，可能減少客製工作。選擇取決於所需應用、會計方式、整合、託管、升級要求和維護責任。透過認真設定，Odoo 可管理庫存、採購、多倉庫、CRM、現場服務、會員和訂閱。', example: '批發訂單可自動預留庫存、建立出貨任務、顯示補貨需求並套用客戶專屬價格，不必在多個工具重複輸入。管理者可從同一業務記錄查看銷售、可用庫存、在途採購和異常，而不是事後拼接試算表。', limits: 'Odoo 無法彌補模糊流程或低品質資料。範圍失控、用戶未參與設計、遷移資料未清理、過度客製或上線後停止培訓，都會造成失敗。對只需要基礎會計的小企業，QuickBooks 可能仍然合適；是否替換取決於財務要求、控制、整合和會計團隊。', questions: [['實施需要多久？', '聚焦的第一階段可能需要數週；多公司、製造、複雜整合或大量遷移通常需要數月。範圍和決策速度比模組數量更重要。'], ['需要多少持續支援？', '支援應涵蓋用戶問題、監控、更新、權限變化、整合和受控的改進清單。']] },
      es: { title: '¿Qué es Odoo ERP y cuándo encaja?', description: 'Guía empresarial sobre módulos de Odoo, Community frente a Enterprise, implementación, migración, costos y ajuste.', answer: 'Odoo es una plataforma ERP modular que conecta CRM, ventas, compras, inventario, proyectos, servicio de campo, suscripciones y comercio electrónico alrededor de registros compartidos. Encaja cuando una empresa ha superado hojas de cálculo y herramientas aisladas y está dispuesta a definir el trabajo entre departamentos. Elegir software no crea por sí solo un ERP funcional; el diseño del proceso, la migración, los permisos, la capacitación y el soporte determinan el resultado.', operations: 'Community puede servir a organizaciones con capacidad técnica y necesidades cubiertas por sus módulos. Enterprise agrega funciones comerciales y servicios del proveedor que pueden reducir desarrollo propio. La elección depende de aplicaciones, contabilidad, integraciones, alojamiento, actualizaciones y mantenimiento. Bien configurado, Odoo puede manejar inventario, compras, varios almacenes, CRM, servicio de campo, membresías y suscripciones.', example: 'Un pedido mayorista puede reservar existencias, crear la entrega, mostrar una necesidad de reposición y aplicar precios por cliente sin repetir datos. Los gerentes revisan ventas, inventario disponible, compras entrantes y excepciones desde el mismo registro, en lugar de conciliar hojas después.', limits: 'Odoo no corrige procesos indefinidos ni datos deficientes. El alcance sin control, excluir usuarios, migrar datos sucios, personalizar en exceso o detener la capacitación causan problemas. QuickBooks puede seguir siendo adecuado para una necesidad contable sencilla; reemplazarlo depende de requisitos financieros, controles, integraciones y del equipo contable.', questions: [['¿Cuánto tarda la implementación?', 'Una primera fase enfocada puede durar semanas; varias empresas, manufactura, integraciones complejas o migración extensa pueden requerir meses.'], ['¿Cuánto soporte continuo se necesita?', 'Debe cubrir preguntas, monitoreo, actualizaciones, cambios de acceso, integraciones y una lista controlada de mejoras.']] },
    },
  },
  {
    slug: 'ai-erp', pillar: 'AI + ERP', audience: 'Operations and department managers', related: relatedCore,
    copy: {
      en: { title: 'What does AI + ERP integration actually mean?', description: 'How governed AI can retrieve ERP data, combine it with company knowledge, prepare actions, and preserve human approval.', answer: 'AI + ERP integration means an AI assistant can retrieve permitted operational data from an ERP, combine it with approved company knowledge, explain the result in plain language, and prepare controlled next steps. It does not mean giving a chatbot unrestricted control. Identity, role permissions, data scope, approval thresholds, source citations, and action logs should remain part of the design.', operations: 'Useful patterns include summarizing sales, identifying inactive customers, explaining inventory exceptions, preparing purchasing recommendations, drafting quotations, and helping employees find ERP procedures. Read-only retrieval is usually the safest starting point. Draft actions can follow after validation; sensitive changes, payments, pricing overrides, deletions, and commitments should normally require human approval.', example: 'A sales manager asks which established customers have declined over the last 90 days. The assistant retrieves permitted order history, defines the comparison period, returns the affected accounts with source records, and drafts a follow-up list. It does not contact customers or change pricing until an authorized person reviews the result.', limits: 'ERP data must be accurate, definitions must be agreed, and permissions must match the employee’s real role. Integration depends on available APIs and system architecture. AI can misinterpret ambiguous requests, so financial, legal, safety, employment, and irreversible actions need clear controls or should remain manual.', questions: [['Can AI create quotations?', 'It can prepare a draft from approved customer, product, pricing, and availability data. An authorized employee should review exceptions and release the quotation.'], ['What should not be automated?', 'High-impact actions with unclear rules, weak data, legal judgment, safety consequences, or no practical reversal path should remain human-controlled.']] },
      'zh-cn': { title: 'AI + ERP 集成到底是什么意思？', description: '了解受控 AI 如何读取 ERP 数据、结合企业知识、准备操作并保留人工审批。', answer: 'AI + ERP 集成是指 AI 助手可以读取获准的 ERP 运营数据，与企业批准的知识结合，用清晰语言解释结果，并准备受控的下一步操作。它并不等于让聊天机器人无限制控制业务。身份、角色权限、数据范围、审批门槛、来源引用和操作日志都应纳入设计。', operations: '实用场景包括销售汇总、识别沉睡客户、解释库存异常、准备采购建议、起草报价，以及帮助员工查找 ERP 操作流程。只读检索通常是最安全的起点。验证后可加入草稿操作；付款、价格覆盖、删除和承诺等敏感变更一般应由人工批准。', example: '销售经理询问过去 90 天哪些老客户的销售出现下降。助手读取其获准访问的订单历史，说明比较周期，列出相关客户及来源记录，并起草跟进清单。在授权人员审核之前，它不会联系客户或修改价格。', limits: 'ERP 数据必须准确，指标定义必须一致，权限要符合员工真实职责。集成还取决于可用 API 和系统架构。AI 可能误解含糊请求，因此财务、法律、安全、人事和不可逆操作需要严格控制，或继续由人工完成。', questions: [['AI 能创建报价吗？', '它可以根据批准的客户、产品、价格和库存数据准备草稿。授权员工应审核例外并正式发送报价。'], ['哪些工作不应自动化？', '规则不清、数据薄弱、涉及法律判断或安全后果，或无法实际撤销的高影响操作应由人工控制。']] },
      'zh-tw': { title: 'AI + ERP 整合到底是什麼意思？', description: '了解受控 AI 如何讀取 ERP 資料、結合企業知識、準備操作並保留人工審批。', answer: 'AI + ERP 整合是指 AI 助手可讀取獲准的 ERP 營運資料，與企業核准知識結合，用清晰語言解釋結果，並準備受控的下一步操作。它不等於讓聊天機器人無限制控制業務。身份、角色權限、資料範圍、審批門檻、來源引用和操作日誌都應納入設計。', operations: '實用場景包括銷售摘要、識別沉睡客戶、解釋庫存異常、準備採購建議、起草報價，以及協助員工查找 ERP 操作流程。唯讀檢索通常是最安全的起點。驗證後可加入草稿操作；付款、價格覆蓋、刪除和承諾等敏感變更一般應由人工批准。', example: '銷售經理詢問過去 90 天哪些舊客戶的銷售出現下降。助手讀取其獲准存取的訂單歷史，說明比較週期，列出相關客戶及來源記錄，並起草跟進清單。在授權人員審核之前，它不會聯絡客戶或修改價格。', limits: 'ERP 資料必須準確，指標定義必須一致，權限要符合員工真實職責。整合亦取決於可用 API 和系統架構。AI 可能誤解含糊要求，因此財務、法律、安全、人事和不可逆操作需要嚴格控制，或繼續由人工完成。', questions: [['AI 能建立報價嗎？', '它可根據核准的客戶、產品、價格和庫存資料準備草稿。授權員工應審核例外並正式發出報價。'], ['哪些工作不應自動化？', '規則不清、資料薄弱、涉及法律判斷或安全後果，或無法實際撤銷的高影響操作應由人工控制。']] },
      es: { title: '¿Qué significa realmente integrar IA y ERP?', description: 'Cómo una IA gobernada consulta datos ERP, los combina con conocimiento, prepara acciones y conserva la aprobación humana.', answer: 'Integrar IA y ERP significa que un asistente puede recuperar datos operativos permitidos, combinarlos con conocimiento aprobado, explicar el resultado y preparar pasos controlados. No significa dar control sin límites a un chatbot. Identidad, permisos por función, alcance de datos, niveles de aprobación, citas de fuentes y registros de acciones deben formar parte del diseño.', operations: 'Los usos prácticos incluyen resumir ventas, identificar clientes inactivos, explicar excepciones de inventario, preparar recomendaciones de compra, redactar cotizaciones y localizar procedimientos ERP. La consulta de solo lectura suele ser el inicio más seguro. Después pueden añadirse borradores; pagos, cambios de precio, eliminaciones y compromisos normalmente requieren aprobación humana.', example: 'Un gerente pregunta qué clientes establecidos han disminuido durante 90 días. El asistente consulta el historial permitido, define el período, devuelve cuentas con registros fuente y prepara seguimiento. No contacta clientes ni cambia precios hasta que una persona autorizada revise el resultado.', limits: 'Los datos deben ser correctos, las definiciones acordadas y los permisos coherentes con cada función. La integración depende de API y arquitectura. La IA puede interpretar mal solicitudes ambiguas; acciones financieras, legales, de seguridad, laborales o irreversibles necesitan controles claros o deben seguir manuales.', questions: [['¿Puede crear cotizaciones?', 'Puede preparar un borrador con datos aprobados de cliente, producto, precio y disponibilidad. Una persona autorizada revisa las excepciones.'], ['¿Qué no debe automatizarse?', 'Acciones de alto impacto con reglas poco claras, datos débiles, juicio legal, consecuencias de seguridad o sin reversión práctica.']] },
    },
  },
  {
    slug: 'business-automation', pillar: 'Business Automation', audience: 'Owners and process managers', related: [{ label: 'AI + ERP guide', href: '/resources/ai-erp' }, { label: 'ERP solutions', href: '/erp-solutions' }, { label: 'Discuss a workflow', href: '/contact?service=automation' }],
    copy: {
      en: { title: 'Which business workflows should be automated?', description: 'A practical framework for choosing automation candidates, defining controls, and avoiding automation of broken processes.', answer: 'Good automation candidates are frequent, rule-based, measurable, and reversible. They use reliable data, have a clear owner, and create little value when performed manually. Examples include routing approved documents, creating reminders, preparing recurring invoices, flagging low stock, and moving accepted orders into fulfillment. A process should be understood and stabilized before software accelerates it.', operations: 'Map the trigger, required data, decision rules, exceptions, approval owner, system action, and audit trail. Start with one bounded workflow and compare results against the manual process. Automation can be deterministic, AI-assisted, or both. Use ordinary rules when the decision is exact; use AI only where interpretation adds value and confidence can be checked.', example: 'Instead of automatically ordering every low-stock item, the ERP can calculate replenishment needs and an AI layer can summarize unusual demand or supplier risk. Purchasing receives a prepared recommendation with evidence. A buyer still approves quantities when seasonality, cash flow, or customer commitments require judgment.', limits: 'Do not automate unclear, rarely used, highly political, safety-critical, or irreversible work merely because it is inconvenient. Poor master data and undocumented exceptions create fast, consistent errors. Define ownership, fallback behavior, monitoring, and a way to stop or reverse the workflow.', questions: [['Should we start with AI or ERP?', 'Start with the missing foundation. If operational data is scattered, stabilize ERP and processes first. If records are sound but knowledge is hard to find, private AI may deliver an earlier win.'], ['How do we measure value?', 'Measure cycle time, exception rate, rework, backlog, error correction, and employee handling time before and after the change.']] },
      'zh-cn': { title: '哪些业务流程适合自动化？', description: '选择自动化场景、设置控制并避免自动化错误流程的实用方法。', answer: '适合自动化的流程通常高频、规则明确、可衡量且可撤销。它使用可靠数据，有清晰负责人，而人工重复执行的价值很低。例如：分发批准文件、创建提醒、准备周期发票、提示低库存以及把确认订单转入履约。流程应先被理解和稳定，再由软件加速。', operations: '应明确触发条件、所需数据、判断规则、例外、审批负责人、系统操作和审计记录。先从一个边界清晰的流程开始，并与原人工流程比较结果。自动化可以是固定规则、AI 辅助或两者结合；决定精确时使用普通规则，只有在解释有价值且结果可验证时才使用 AI。', example: '系统不应看到低库存就自动采购。ERP 可以计算补货需求，AI 可以汇总异常需求或供应商风险，采购人员收到带证据的建议。当季节性、现金流或客户承诺需要判断时，采购员仍负责批准数量。', limits: '不要因为工作麻烦，就自动化定义不清、低频、涉及人员关系、安全关键或不可逆的流程。低质量主数据和未记录例外只会更快地产生一致错误。必须明确责任、失败回退、监控以及停止或撤销方法。', questions: [['应该先做 AI 还是 ERP？', '先补足缺失的基础。运营数据分散时先稳定 ERP；记录可靠但知识难找时，私有 AI 可能更快产生价值。'], ['如何衡量价值？', '在实施前后比较周期时间、例外率、返工、积压、纠错和员工处理时间。']] },
      'zh-tw': { title: '哪些業務流程適合自動化？', description: '選擇自動化場景、設定控制並避免自動化錯誤流程的實用方法。', answer: '適合自動化的流程通常高頻、規則明確、可衡量且可撤銷。它使用可靠資料，有清晰負責人，而人工重複執行的價值很低。例如：分發核准文件、建立提醒、準備週期發票、提示低庫存及把確認訂單轉入履約。流程應先被理解和穩定，再由軟體加速。', operations: '應明確觸發條件、所需資料、判斷規則、例外、審批負責人、系統操作和審計記錄。先從一個邊界清晰的流程開始，並與原人工流程比較結果。自動化可以是固定規則、AI 輔助或兩者結合；決定精確時使用普通規則，只有在解釋有價值且結果可驗證時才使用 AI。', example: '系統不應看到低庫存就自動採購。ERP 可計算補貨需求，AI 可摘要異常需求或供應商風險，採購人員收到附有證據的建議。當季節性、現金流或客戶承諾需要判斷時，採購員仍負責批准數量。', limits: '不要因為工作麻煩，就自動化定義不清、低頻、涉及人員關係、安全關鍵或不可逆的流程。低品質主資料和未記錄例外只會更快產生一致錯誤。必須明確責任、失敗回退、監控以及停止或撤銷方法。', questions: [['應該先做 AI 還是 ERP？', '先補足缺失的基礎。營運資料分散時先穩定 ERP；記錄可靠但知識難找時，私有 AI 可能更快產生價值。'], ['如何衡量價值？', '在實施前後比較週期時間、例外率、返工、積壓、糾錯和員工處理時間。']] },
      es: { title: '¿Qué procesos empresariales conviene automatizar?', description: 'Marco práctico para elegir automatizaciones, definir controles y evitar acelerar procesos defectuosos.', answer: 'Los buenos candidatos son frecuentes, basados en reglas, medibles y reversibles. Usan datos confiables, tienen responsable claro y aportan poco valor al ejecutarse manualmente. Ejemplos: distribuir documentos aprobados, crear recordatorios, preparar facturas recurrentes, avisar inventario bajo y mover pedidos aceptados a entrega. Primero se entiende y estabiliza el proceso; después se acelera.', operations: 'Defina disparador, datos, reglas, excepciones, aprobador, acción del sistema y registro. Empiece con un flujo limitado y compare contra el proceso manual. La automatización puede ser determinista, asistida por IA o ambas. Use reglas normales cuando la decisión sea exacta; use IA solo cuando interpretar agregue valor y la confianza pueda verificarse.', example: 'En lugar de comprar automáticamente todo artículo bajo, el ERP calcula reposición y la IA resume demanda inusual o riesgo del proveedor. Compras recibe una recomendación con evidencia. Una persona aprueba cantidades cuando estacionalidad, efectivo o compromisos requieren criterio.', limits: 'No automatice trabajo poco claro, raro, políticamente sensible, crítico para la seguridad o irreversible solo porque molesta. Datos deficientes y excepciones no documentadas producen errores más rápidos. Defina propietario, recuperación, monitoreo y cómo detener o revertir.', questions: [['¿Empezamos con IA o ERP?', 'Empiece por la base ausente. Si los datos están dispersos, estabilice ERP y procesos; si los registros son sólidos pero el conocimiento no aparece, la IA privada puede ganar antes.'], ['¿Cómo medimos valor?', 'Compare tiempo de ciclo, excepciones, retrabajo, atraso, correcciones y tiempo de gestión antes y después.']] },
    },
  },
  {
    slug: 'comparisons', pillar: 'Comparisons', audience: 'Owners evaluating technology options', related: [{ label: 'Private AI guide', href: '/resources/private-ai' }, { label: 'Odoo ERP guide', href: '/resources/odoo-erp' }, { label: 'Pricing', href: '/pricing' }],
    copy: {
      en: { title: 'Private AI, public AI, and ERP choices compared', description: 'Fair comparisons for Private AI versus ChatGPT, local versus cloud AI, Odoo editions, and Odoo versus QuickBooks.', answer: 'There is no universal winner. Public AI tools are convenient for general work that does not expose restricted information. Private AI is appropriate when a company needs controlled knowledge, permissions, deployment choices, and integration. Odoo Community can fit technically capable organizations with simpler requirements; Enterprise can reduce gaps through commercial features. QuickBooks can remain the better accounting tool when broader operational integration is unnecessary.', operations: 'Compare options against the same questions: What data may the system access? Who operates and updates it? Which business workflows must connect? What happens during an outage? What licenses, infrastructure, implementation, and support are required? A low subscription price can still produce a high operating cost when employees reconcile systems manually; a broad platform can be excessive when the business only needs reliable bookkeeping.', example: 'A ten-person professional-services firm may reasonably keep QuickBooks and use controlled cloud AI for approved documents. A distributor with several warehouses, customer pricing, purchasing, returns, and confidential SOPs may benefit from Odoo plus private AI. The decision comes from process complexity and control requirements, not company size alone.', limits: 'Product editions and commercial terms change, so current vendor documentation must be reviewed before purchase. Security depends on configuration, identity, data handling, and operations—not merely the words “local,” “cloud,” or “private.” Nexavoris should validate integrations and licensing during discovery rather than promise equivalence.', questions: [['Is private AI always safer than ChatGPT?', 'No. A poorly maintained local system can be less secure than a well-governed cloud service. Compare actual data flows, retention, access, administration, and contracts.'], ['Can Odoo replace QuickBooks?', 'Sometimes. Confirm accounting requirements, reporting, payroll dependencies, controls, migration, and the accountant’s workflow before deciding.']] },
      'zh-cn': { title: '私有 AI、公共 AI 与 ERP 方案比较', description: '公平比较私有 AI 与 ChatGPT、本地与云 AI、Odoo 版本以及 Odoo 与 QuickBooks。', answer: '没有适合所有企业的唯一赢家。公共 AI 工具适合不涉及受限信息的一般工作；当企业需要受控知识、权限、部署选择和系统集成时，私有 AI 更合适。拥有技术能力且需求较简单的企业可能适合 Odoo 社区版；企业版可通过商业功能减少功能缺口。如果无需更广泛的运营集成，QuickBooks 仍可能是更合适的会计工具。', operations: '应使用相同问题比较方案：系统能访问哪些数据？谁负责运行和更新？必须连接哪些业务流程？停机时怎么办？许可证、基础设施、实施和支持成本是多少？低订阅价格不代表低运营成本；员工每天手工对账也会产生高成本。业务只需要可靠记账时，广泛平台也可能过度。', example: '一家十人的专业服务公司可能合理地保留 QuickBooks，并使用受控云 AI 处理批准文档。拥有多个仓库、客户价格、采购、退货和机密 SOP 的分销商则可能适合 Odoo 加私有 AI。决定来自流程复杂度和控制要求，而不只是员工人数。', limits: '产品版本和商业条款会变化，采购前必须查看最新厂商资料。安全取决于配置、身份、数据处理和运营，而不只是“本地”“云”或“私有”等标签。Nexavoris 应在发现阶段验证集成和许可，不应承诺完全等价。', questions: [['私有 AI 一定比 ChatGPT 安全吗？', '不一定。维护不当的本地系统可能不如治理良好的云服务安全。应比较真实数据流、保留、访问、管理和合同。'], ['Odoo 能替代 QuickBooks 吗？', '有时可以。决定前应确认会计要求、报表、工资依赖、控制、迁移和会计人员流程。']] },
      'zh-tw': { title: '私有 AI、公共 AI 與 ERP 方案比較', description: '公平比較私有 AI 與 ChatGPT、本地與雲端 AI、Odoo 版本以及 Odoo 與 QuickBooks。', answer: '沒有適合所有企業的唯一贏家。公共 AI 工具適合不涉及受限資訊的一般工作；當企業需要受控知識、權限、部署選擇和系統整合時，私有 AI 更合適。擁有技術能力且需求較簡單的企業可能適合 Odoo 社群版；企業版可透過商業功能減少功能缺口。如果不需要更廣泛的營運整合，QuickBooks 仍可能是更合適的會計工具。', operations: '應使用相同問題比較方案：系統能存取哪些資料？誰負責運行和更新？必須連接哪些業務流程？停機時怎麼辦？授權、基礎設施、實施和支援成本是多少？低訂閱價格不代表低營運成本；員工每天手工對帳亦會產生高成本。業務只需要可靠記帳時，廣泛平台也可能過度。', example: '一家十人的專業服務公司可能合理地保留 QuickBooks，並使用受控雲端 AI 處理核准文件。擁有多個倉庫、客戶價格、採購、退貨和機密 SOP 的分銷商則可能適合 Odoo 加私有 AI。決定來自流程複雜度和控制要求，而不只是員工人數。', limits: '產品版本和商業條款會變化，採購前必須查看最新廠商資料。安全取決於設定、身份、資料處理和營運，而不只是「本地」「雲端」或「私有」等標籤。Nexavoris 應在探索階段驗證整合和授權，不應承諾完全等價。', questions: [['私有 AI 一定比 ChatGPT 安全嗎？', '不一定。維護不當的本地系統可能不如治理良好的雲端服務安全。應比較真實資料流、保留、存取、管理和合約。'], ['Odoo 能替代 QuickBooks 嗎？', '有時可以。決定前應確認會計要求、報表、薪資依賴、控制、遷移和會計人員流程。']] },
      es: { title: 'Comparación de IA privada, IA pública y opciones ERP', description: 'Comparación equilibrada: IA privada frente a ChatGPT, IA local o nube, ediciones de Odoo y Odoo frente a QuickBooks.', answer: 'No existe un ganador universal. La IA pública es práctica para trabajo general sin información restringida. La IA privada encaja cuando se necesitan conocimiento controlado, permisos, opciones de despliegue e integración. Odoo Community puede servir a organizaciones técnicas con necesidades sencillas; Enterprise puede reducir brechas con funciones comerciales. QuickBooks puede seguir siendo mejor cuando no se necesita integración operativa amplia.', operations: 'Compare con las mismas preguntas: ¿qué datos puede usar?, ¿quién lo administra?, ¿qué procesos conecta?, ¿qué ocurre durante una interrupción?, ¿qué licencias, infraestructura, implementación y soporte requiere? Una suscripción barata puede tener alto costo operativo si el personal concilia sistemas manualmente; una plataforma amplia puede sobrar si solo se necesita contabilidad confiable.', example: 'Una firma profesional de diez personas puede conservar QuickBooks y usar IA controlada en la nube para documentos aprobados. Un distribuidor con varios almacenes, precios por cliente, compras, devoluciones y procedimientos confidenciales puede beneficiarse de Odoo más IA privada. La decisión depende del proceso y control, no solo del tamaño.', limits: 'Ediciones y términos cambian; revise documentación vigente antes de comprar. La seguridad depende de configuración, identidad, datos y operación, no solo de las palabras “local”, “nube” o “privada”. Nexavoris debe validar integraciones y licencias durante el descubrimiento.', questions: [['¿La IA privada siempre es más segura que ChatGPT?', 'No. Un sistema local mal mantenido puede ser menos seguro que una nube bien gobernada. Compare flujo, retención, acceso, administración y contratos.'], ['¿Odoo puede reemplazar QuickBooks?', 'A veces. Confirme contabilidad, informes, nómina, controles, migración y el trabajo del contador.']] },
    },
  },
  {
    slug: 'guides', pillar: 'Buyer Guides', audience: 'Owners preparing a budget or discovery process', related: [{ label: 'Current planning prices', href: '/pricing' }, { label: 'Equipment guidance', href: '/equipment' }, { label: 'Book discovery', href: '/contact' }],
    copy: {
      en: { title: 'Planning cost, timing, and scope for AI and ERP', description: 'A buyer guide to Private AI cost, Odoo implementation cost, AI + ERP timing, discovery inputs, and ongoing support.', answer: 'Private AI and ERP budgets are driven less by labels than by scope. Important drivers include users, companies, documents, data quality, workflows, permissions, integrations, infrastructure, migration, training, rollout, and support. Nexavoris publishes planning-level packages on its pricing page; a binding estimate requires discovery because two businesses with the same employee count can have very different operating complexity.', operations: 'A useful discovery package includes process owners, current systems, representative documents, data samples, user roles, required reports, integration endpoints, known exceptions, security expectations, and the business outcome to improve. A focused first phase can take weeks. Multi-company ERP, manufacturing, extensive migration, dedicated AI infrastructure, or complex approvals can take months and should be staged.', example: 'A company may start with one department’s approved SOP library and read-only ERP reporting before adding draft actions. Another may first clean customer, product, vendor, and inventory records and implement the ERP transaction flow. Starting with the weakest foundation reduces rework and gives the team a result it can validate.', limits: 'Do not budget only for software or hardware. Include process decisions, data cleanup, testing, employee time, training, change management, backup, monitoring, updates, and improvement. Exact pricing, security architecture, hardware capacity, and delivery dates require human review after the current environment is understood.', questions: [['How many employees justify private AI?', 'Employee count alone is weak. Repeated knowledge questions, document sensitivity, search time, permission complexity, and the cost of inconsistent answers are better signals.'], ['How much support is required?', 'At minimum, assign ownership for users, content, access, integrations, incidents, updates, backups, and measured improvements.']] },
      'zh-cn': { title: '规划 AI 与 ERP 的成本、时间和范围', description: '涵盖私有 AI 成本、Odoo 实施成本、AI + ERP 周期、发现资料和持续支持的采购指南。', answer: '私有 AI 与 ERP 预算主要由范围决定，而不是方案名称。关键因素包括用户、公司数量、文档、数据质量、流程、权限、集成、基础设施、迁移、培训、上线和支持。Nexavoris 在价格页面提供规划级套餐；正式报价需要先做发现，因为员工数量相同的企业也可能拥有完全不同的运营复杂度。', operations: '有效的发现资料应包括流程负责人、现有系统、代表性文档、数据样本、用户角色、必需报表、集成接口、已知例外、安全要求和要改善的业务结果。聚焦的第一阶段可能需要数周；多公司 ERP、制造、大量迁移、专用 AI 基础设施或复杂审批可能需要数月，应分阶段实施。', example: '企业可以先从一个部门的批准 SOP 和只读 ERP 报表开始，再加入草稿操作。另一家企业可能应先清理客户、产品、供应商和库存记录，并建立 ERP 交易流程。从最薄弱的基础开始可减少返工，也让团队更容易验证结果。', limits: '预算不能只包含软件或硬件。还要包括流程决策、数据清理、测试、员工时间、培训、变更管理、备份、监控、更新和改进。准确价格、安全架构、硬件容量和交付日期必须在了解现状后由人员审核。', questions: [['多少员工才值得使用私有 AI？', '员工人数本身不是好指标。重复知识问题、文档敏感度、查找时间、权限复杂度和不一致答案的成本更重要。'], ['需要多少持续支持？', '至少要明确用户、内容、访问、集成、事件、更新、备份和持续改进的负责人。']] },
      'zh-tw': { title: '規劃 AI 與 ERP 的成本、時間和範圍', description: '涵蓋私有 AI 成本、Odoo 實施成本、AI + ERP 週期、探索資料和持續支援的採購指南。', answer: '私有 AI 與 ERP 預算主要由範圍決定，而不是方案名稱。關鍵因素包括用戶、公司數量、文件、資料品質、流程、權限、整合、基礎設施、遷移、培訓、上線和支援。Nexavoris 在價格頁面提供規劃級方案；正式報價需要先做探索，因為員工數量相同的企業也可能擁有完全不同的營運複雜度。', operations: '有效的探索資料應包括流程負責人、現有系統、代表性文件、資料樣本、用戶角色、必需報表、整合介面、已知例外、安全要求和要改善的業務結果。聚焦的第一階段可能需要數週；多公司 ERP、製造、大量遷移、專用 AI 基礎設施或複雜審批可能需要數月，應分階段實施。', example: '企業可先從一個部門的核准 SOP 和唯讀 ERP 報表開始，再加入草稿操作。另一家企業可能應先清理客戶、產品、供應商和庫存記錄，並建立 ERP 交易流程。從最薄弱的基礎開始可減少返工，也讓團隊更容易驗證結果。', limits: '預算不能只包含軟體或硬體。還要包括流程決策、資料清理、測試、員工時間、培訓、變更管理、備份、監控、更新和改進。準確價格、安全架構、硬體容量和交付日期必須在了解現況後由人員審核。', questions: [['多少員工才值得使用私有 AI？', '員工人數本身不是好指標。重複知識問題、文件敏感度、查找時間、權限複雜度和不一致答案的成本更重要。'], ['需要多少持續支援？', '至少要明確用戶、內容、存取、整合、事件、更新、備份和持續改進的負責人。']] },
      es: { title: 'Planificación de costo, tiempo y alcance para IA y ERP', description: 'Guía de compra sobre costos de IA privada y Odoo, plazos de IA + ERP, descubrimiento y soporte continuo.', answer: 'Los presupuestos de IA privada y ERP dependen más del alcance que del nombre del paquete. Influyen usuarios, empresas, documentos, calidad de datos, procesos, permisos, integraciones, infraestructura, migración, capacitación, lanzamiento y soporte. Nexavoris publica niveles orientativos; una estimación vinculante requiere descubrimiento porque dos empresas del mismo tamaño pueden tener complejidad muy distinta.', operations: 'Un buen paquete de descubrimiento incluye responsables, sistemas actuales, documentos y datos de muestra, funciones, informes, integraciones, excepciones, seguridad y el resultado que se desea mejorar. Una primera fase enfocada puede durar semanas. Varias empresas, manufactura, migración extensa, infraestructura dedicada o aprobaciones complejas pueden requerir meses y deben dividirse.', example: 'Una empresa puede empezar con procedimientos aprobados de un departamento e informes ERP de solo lectura antes de añadir borradores de acciones. Otra puede necesitar limpiar clientes, productos, proveedores e inventario e implantar primero el flujo ERP. Empezar por la base más débil reduce retrabajo.', limits: 'No presupueste solo software o hardware. Incluya decisiones de proceso, limpieza, pruebas, tiempo del personal, capacitación, cambio, copias, monitoreo, actualizaciones y mejora. Precio exacto, seguridad, capacidad y fechas requieren revisión humana después de entender el entorno.', questions: [['¿Cuántos empleados justifican IA privada?', 'El número por sí solo dice poco. Importan preguntas repetidas, sensibilidad, tiempo de búsqueda, permisos y costo de respuestas inconsistentes.'], ['¿Cuánto soporte se necesita?', 'Como mínimo, asigne responsables de usuarios, contenido, acceso, integraciones, incidentes, actualizaciones, copias y mejora.']] },
    },
  },
];

export const industryDefinitions = [
  ['wholesale-distribution','Wholesale & Distribution','库存准确性、客户价格、采购、补货、履约、退货和仓库 SOP','庫存準確性、客戶價格、採購、補貨、履約、退貨和倉庫 SOP','exactitud de inventario, precios por cliente, compras, reposición, entregas, devoluciones y procedimientos de almacén'],
  ['hvac-field-service','HVAC & Field Service','调度、设备历史、会员计划、零件、保修、现场流程和发票','調度、設備歷史、會員計劃、零件、保養、現場流程和發票','despacho, historial de equipos, membresías, repuestos, garantías, procedimientos de campo y facturación'],
  ['construction','Construction','项目成本、变更单、采购承诺、现场文件、进度和批准','項目成本、變更單、採購承諾、現場文件、進度和批准','costos de obra, órdenes de cambio, compromisos, documentos de campo, avance y aprobaciones'],
  ['manufacturing','Manufacturing','物料需求、生产计划、工单、质量程序、版本控制和停机异常','物料需求、生產計劃、工單、品質程序、版本控制和停機異常','materiales, planificación, órdenes de trabajo, calidad, control de revisiones y excepciones de producción'],
  ['retail','Retail','多门店库存、商品、采购、退货、客户记录和补货','多門店庫存、商品、採購、退貨、客戶記錄和補貨','inventario multitienda, productos, compras, devoluciones, clientes y reposición'],
  ['professional-services','Professional Services','商机、项目范围、资源、工时、交付标准、周期工作和开票','商機、項目範圍、資源、工時、交付標準、週期工作和開票','oportunidades, alcance, recursos, tiempo, estándares de entrega, trabajo recurrente y facturación'],
] as const;

for (const [slug, name, cnFocus, twFocus, esFocus] of industryDefinitions) {
  const enFocus: Record<string,string> = {
    'wholesale-distribution':'inventory accuracy, customer-specific pricing, purchasing, replenishment, fulfillment, returns, and warehouse procedures',
    'hvac-field-service':'dispatch, equipment history, maintenance plans, parts, warranties, field procedures, and invoicing',
    construction:'job cost, change orders, purchasing commitments, field documents, schedule, and approvals',
    manufacturing:'material requirements, production planning, work orders, quality procedures, revision control, and production exceptions',
    retail:'multi-location inventory, products, purchasing, returns, customer records, and replenishment',
    'professional-services':'opportunities, scope, resources, time, delivery standards, recurring work, and billing',
  };
  resourceEntries.push({ slug:`industries/${slug}`, pillar:'Industries', audience:'Owners and operations managers', related:[...relatedCore,{label:'All industries',href:'/industries'}], copy:{
    en:{title:`AI, ERP, and automation for ${name}`,description:`A practical guide to ${enFocus[slug]} for ${name.toLowerCase()} businesses.`,answer:`For ${name.toLowerCase()} businesses, useful technology starts with the operating record: ${enFocus[slug]}. ERP should make that record consistent across teams. Private AI can help employees retrieve approved procedures and explain permitted information. Automation can move routine handoffs, but judgment, exceptions, and high-impact approvals remain with responsible people.`,operations:`Start by mapping the work from customer request through delivery and payment. Identify where data is re-entered, where managers wait for reports, which questions interrupt experienced employees, and which exceptions create risk. Configure the ERP around the shared transaction flow, then add knowledge search and bounded automation where they solve a measured problem.`,example:`A manager should be able to see current work, the records behind it, and the exceptions needing attention without assembling several spreadsheets. An employee should be able to find the approved procedure without guessing which folder is current. Nexavoris connects those needs while preserving role-based access and approval responsibility.`,limits:`Not every task needs AI. Exact calculations, required approvals, and stable routing rules often belong in ERP logic. AI is most useful for finding, summarizing, and preparing information where sources can be cited. Implementation scope depends on data quality, integrations, user roles, and the number of operating locations.`,questions:[[ `What should ${name} implement first?`,'Begin with the workflow causing the most repeated delay or unreliable reporting, while making sure its source data and owner are defined.'],['Can AI make operating decisions automatically?','It can prepare evidence and recommendations. Material commitments, safety decisions, pricing exceptions, and irreversible actions should retain human approval.']]},
    'zh-cn':{title:`面向${name}的 AI、ERP 与自动化`,description:`围绕${cnFocus}的实用业务指南。`,answer:`对于该行业，有用的技术应从真实运营记录开始，包括${cnFocus}。ERP 让不同团队使用一致记录；私有 AI 帮助员工检索批准的流程并解释其有权查看的信息；自动化负责常规交接，但判断、例外和高影响审批仍由负责人完成。`,operations:'先梳理从客户需求、交付到收款的完整流程。找出重复录入、管理者等待报表、员工频繁打断资深同事以及例外风险的位置。围绕共享交易流程配置 ERP，再在能够解决可衡量问题的位置加入知识检索和边界清晰的自动化。',example:'管理者应能看到当前工作、相关记录和需要处理的异常，而不必拼接多个表格。员工应能找到批准流程，不必猜测哪个文件夹最新。Nexavoris 连接这些需求，同时保留角色权限和审批责任。',limits:'并非每项工作都需要 AI。精确计算、强制审批和稳定路由规则通常应由 ERP 逻辑处理。AI 更适合在能够引用来源时查找、汇总和准备信息。实施范围取决于数据质量、集成、用户角色和运营地点数量。',questions:[['应该先实施什么？','从造成最多重复延误或报表不可靠的流程开始，同时先明确数据来源和负责人。'],['AI 能自动做运营决定吗？','它可以准备证据和建议。重大承诺、安全决定、价格例外和不可逆操作应保留人工审批。']]},
    'zh-tw':{title:`面向${name}的 AI、ERP 與自動化`,description:`圍繞${twFocus}的實用業務指南。`,answer:`對該行業而言，有用的技術應從真實營運記錄開始，包括${twFocus}。ERP 讓不同團隊使用一致記錄；私有 AI 協助員工檢索核准流程並解釋其有權查看的資訊；自動化負責常規交接，但判斷、例外和高影響審批仍由負責人完成。`,operations:'先梳理從客戶需求、交付到收款的完整流程。找出重複輸入、管理者等待報表、員工頻繁打斷資深同事以及例外風險的位置。圍繞共享交易流程設定 ERP，再在能解決可衡量問題的位置加入知識檢索和邊界清晰的自動化。',example:'管理者應能看到目前工作、相關記錄和需要處理的異常，而不必拼接多個試算表。員工應能找到核准流程，不必猜測哪個資料夾最新。Nexavoris 連接這些需求，同時保留角色權限和審批責任。',limits:'並非每項工作都需要 AI。精確計算、強制審批和穩定路由規則通常應由 ERP 邏輯處理。AI 更適合在能引用來源時查找、摘要和準備資訊。實施範圍取決於資料品質、整合、用戶角色和營運地點數量。',questions:[['應該先實施什麼？','從造成最多重複延誤或報表不可靠的流程開始，同時先明確資料來源和負責人。'],['AI 能自動做營運決定嗎？','它可準備證據和建議。重大承諾、安全決定、價格例外和不可逆操作應保留人工審批。']]},
    es:{title:`IA, ERP y automatización para ${name}`,description:`Guía práctica sobre ${esFocus} para empresas de este sector.`,answer:`En este sector, la tecnología útil empieza con el registro operativo: ${esFocus}. El ERP mantiene un registro consistente entre equipos. La IA privada ayuda a recuperar procedimientos aprobados y explicar información permitida. La automatización mueve traspasos rutinarios, pero el criterio, las excepciones y aprobaciones importantes siguen con personas responsables.`,operations:'Primero se mapea el trabajo desde la solicitud del cliente hasta entrega y cobro. Se identifica dónde se repiten datos, dónde los gerentes esperan informes, qué preguntas interrumpen a empleados expertos y qué excepciones crean riesgo. Después se configura el ERP y se añade búsqueda o automatización limitada donde resuelva un problema medido.',example:'Un gerente debe ver trabajo actual, registros y excepciones sin unir varias hojas. Un empleado debe encontrar el procedimiento aprobado sin adivinar qué carpeta está vigente. Nexavoris conecta esas necesidades conservando acceso por función y responsabilidad de aprobación.',limits:'No toda tarea necesita IA. Cálculos exactos, aprobaciones obligatorias y reglas estables suelen pertenecer al ERP. La IA resulta más útil para localizar, resumir y preparar información con fuentes. El alcance depende de calidad de datos, integraciones, funciones y ubicaciones.',questions:[['¿Qué conviene implementar primero?','Empiece con el flujo que causa más retraso repetido o informes poco confiables, después de definir su fuente de datos y responsable.'],['¿Puede la IA decidir automáticamente?','Puede preparar evidencia y recomendaciones. Compromisos, seguridad, excepciones de precio y acciones irreversibles deben conservar aprobación humana.']]},
  }});
}

export const resourceBySlug = new Map(resourceEntries.map((entry) => [entry.slug, entry]));
