import type { AssessmentAnswers, Scores } from '@/lib/member-tools';

export type RestaurantType='makeToOrder'|'chineseBuffet'|'hybrid';
export type RestaurantCategory='foodCost'|'purchasing'|'inventory'|'operations'|'waste'|'labor'|'pos'|'customer'|'reporting'|'training'|'accounting'|'ai';
export type RestaurantScores=Scores&{restaurant:true;restaurantType:RestaurantType;categories:Record<RestaurantCategory,number>;health:Record<'foodCost'|'labor'|'inventory'|'waste'|'technology'|'aiReadiness'|'ownerIndependence',number>;status:string};
export type DerivedMetric={label:string;value:string;note?:string};
export type DiagnosticRecommendation={title:string;priority:'Critical'|'High'|'Medium'|'Low';impact:string;difficulty:'Easy'|'Moderate'|'Advanced';timeline:'0–30 days'|'30–90 days'|'3–6 months'|'6–12 months';reason:string;solution:string};
export type ProfitLeakage={areas:readonly (readonly [string,readonly [number,number],string])[];total:readonly [number,number];disclaimer:string};

export const categoryLabels:Record<RestaurantCategory,string>={foodCost:'Food Cost & Recipe Control',purchasing:'Purchasing & Vendor Management',inventory:'Food & Ingredient Inventory',operations:'Kitchen & Service Operations',waste:'Waste & Shrinkage',labor:'Labor & Scheduling',pos:'POS & Order Integration',customer:'Customer & Marketing',reporting:'Management Reporting',training:'Employee Training & SOP',accounting:'Accounting & Financial Integration',ai:'AI & Automation Readiness'};
export const restaurantTypeLabels:Record<RestaurantType,string>={makeToOrder:'Make-to-Order Restaurant',chineseBuffet:'Chinese Buffet Restaurant',hybrid:'Hybrid Restaurant'};
export const list=(value:unknown)=>(typeof value==='string'||typeof value==='number'?String(value):'').split('|').filter(Boolean);
export const num=(answers:AssessmentAnswers,id:string)=>{const value=Number(String(answers[id]??'').replace(/[$,%\s,]/g,''));return Number.isFinite(value)&&value>=0?value:0};
const rangeMidpoints:Record<string,number>={
 'sales-under-50k':40000,'sales-50-100k':75000,'sales-100-250k':175000,'sales-250-500k':375000,'sales-500k+':600000,
 'food-under-15k':12000,'food-15-30k':22500,'food-30-75k':52500,'food-75-150k':112500,'food-150k+':180000,
 'payroll-under-15k':12000,'payroll-15-30k':22500,'payroll-30-75k':52500,'payroll-75-150k':112500,'payroll-150k+':180000,
 'customers-under-1500':1200,'customers-1500-3000':2250,'customers-3000-7500':5250,'customers-7500-15000':11250,'customers-15000+':18000,
 'waste-under-1k':750,'waste-1-3k':2000,'waste-3-7k':5000,'waste-7-15k':11000,'waste-15k+':18000,
};
export const financialValue=(answers:AssessmentAnswers,exactId:string,rangeId:string)=>num(answers,exactId)||rangeMidpoints[String(answers[rangeId]??'')]||0;
const yn=(answers:AssessmentAnswers,id:string)=>answers[id]==='yes'?3:answers[id]==='partly'?2:answers[id]==='no'?0:1;
const freq=(value:unknown)=>({'daily':3,'weekly':3,'monthly':2,'occasionally':1,'never':0}[String(value)]??1);
const average=(values:number[])=>Math.round(values.reduce((a,b)=>a+b,0)/Math.max(1,values.length)/3*100);

export function scoreRestaurantAssessment(a:AssessmentAnswers):RestaurantScores{
 const type=(a.restaurantType||'makeToOrder') as RestaurantType;
 const foodCost=average([yn(a,'targetFoodCost'),freq(a.foodCostFrequency),list(a.foodCostTracking).length>=3?3:list(a.foodCostTracking).length?2:0,type==='chineseBuffet'?yn(a,'buffetCostPerCustomer'):yn(a,'exactMenuCost')]);
 const purchasing=average([yn(a,'compareVendors'),yn(a,'vendorHistory'),yn(a,'vendorPriceAlerts'),a.purchaseOrderMethod==='Formal PO'?3:a.purchaseOrderMethod==='No formal process'?0:1]);
 const inventory=average([freq(a.inventoryFrequency),['POS','ERP'].includes(String(a.inventoryLocation))?3:a.inventoryLocation==='Spreadsheet'?2:a.inventoryLocation==='No formal tracking'?0:1,list(a.inventoryControls).length>=4?3:list(a.inventoryControls).length>=2?2:list(a.inventoryControls).length?1:0]);
 const operations=average([yn(a,'systemsConnected'),yn(a,'remotePerformance'),type==='makeToOrder'?yn(a,'recipesStandardized'):yn(a,'smallerClosingTrays')]);
 const waste=average([a.wasteRecording==='System'?3:a.wasteRecording==='Spreadsheet'?2:a.wasteRecording==='Paper log'?1:0,yn(a,'wasteReviewed'),num(a,'monthlyWaste')>0?2:1]);
 const labor=average([list(a.laborTracking).length>=4?3:list(a.laborTracking).length>=2?2:list(a.laborTracking).length?1:0,['POS scheduling module','Dedicated scheduling software'].includes(String(a.schedulingMethod))?3:a.schedulingMethod==='Spreadsheet'?2:1,yn(a,'scheduleForecast')]);
 const pos=average([yn(a,'systemsConnected'),yn(a,'duplicateEntry')===0?3:0,num(a,'systemsCount')<=2?3:num(a,'systemsCount')<=4?2:1]);
 const customer=average([num(a,'directOrderingPct')>=20?3:num(a,'directOrderingPct')>0?2:1,num(a,'thirdPartyPct')<=15?3:num(a,'thirdPartyPct')<=25?2:1]);
 const reporting=average([list(a.reports).length>=7?3:list(a.reports).length>=3?2:list(a.reports).length?1:0,a.reportFrequency==='Real-time'?3:a.reportFrequency==='Daily'?2:a.reportFrequency==='Weekly'?1:0,yn(a,'remotePerformance')]);
 const training=average([yn(a,'proceduresDigital'),yn(a,'recipesDigital'),num(a,'ownerIndependence')>=4?3:num(a,'ownerIndependence')>=3?2:1]);
 const accounting=average([['QuickBooks','Xero','Odoo'].includes(String(a.accountingSystem))?3:a.accountingSystem==='Spreadsheet'?1:2,yn(a,'duplicateEntry')===0?3:1]);
 const ai=average([yn(a,'proceduresDigital'),yn(a,'historicalPos'),yn(a,'digitalPurchasing'),yn(a,'inventoryHistory'),list(a.aiData).length>=4?3:list(a.aiData).length>=2?2:list(a.aiData).length?1:0]);
 const categories={foodCost,purchasing,inventory,operations,waste,labor,pos,customer,reporting,training,accounting,ai};
 const weights:Record<RestaurantCategory,number>=type==='chineseBuffet'?{foodCost:12,purchasing:10,inventory:10,operations:12,waste:15,labor:7,pos:7,customer:0,reporting:8,training:5,accounting:5,ai:9}:{foodCost:15,purchasing:10,inventory:10,operations:10,waste:8,labor:8,pos:10,customer:5,reporting:8,training:6,accounting:5,ai:5};
 if(type==='hybrid'){weights.waste=12;weights.operations=11;weights.customer=3;weights.ai=7}
 const totalWeight=Object.values(weights).reduce((x,y)=>x+y,0);const overall=Math.round((Object.keys(weights) as RestaurantCategory[]).reduce((sum,key)=>sum+categories[key]*weights[key],0)/totalWeight);
 const ownerIndependence=Math.min(100,Math.round(num(a,'ownerIndependence')/5*100));
 return{restaurant:true,restaurantType:type,categories,health:{foodCost,labor,inventory,waste,technology:Math.round((pos+accounting+reporting)/3),aiReadiness:ai,ownerIndependence},status:overall<40?'Critical Operational Gaps':overall<60?'High Improvement Opportunity':overall<80?'Growth Ready':'Digitally Advanced',overall,ai,erp:Math.round((purchasing+inventory+accounting+reporting)/4),automation:Math.round((operations+waste+labor+pos)/4),data:Math.round((inventory+reporting+accounting+ai)/4)};
}

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function restaurantDerivedMetrics(a:AssessmentAnswers):DerivedMetric[]{
 const monthly=financialValue(a,'monthlySales','monthlySalesRange'),food=financialValue(a,'monthlyFoodPurchases','monthlyFoodRange'),payroll=financialValue(a,'monthlyPayroll','monthlyPayrollRange'),transactions=num(a,'monthlyTransactions'),customers=financialValue(a,'monthlyCustomerCount','monthlyCustomerRange')||num(a,'customersPerDay')*30,waste=financialValue(a,'monthlyWaste','monthlyWasteRange');const locations=Math.max(1,num(a,'locationCount')||1);const employees=['kitchenEmployees','servers','cashiers','managers','deliveryStaff','otherEmployees'].reduce((s,k)=>s+num(a,k),0);
 const metrics:DerivedMetric[]=[];if(monthly)metrics.push({label:'Estimated annual revenue',value:money(monthly*12),note:'Estimated based on information provided.'});if(monthly&&food)metrics.push({label:'Estimated food cost',value:`${(food/monthly*100).toFixed(1)}%`,note:`${money(food)} monthly purchases ÷ ${money(monthly)} sales`});if(monthly&&payroll)metrics.push({label:'Estimated labor cost',value:`${(payroll/monthly*100).toFixed(1)}%`,note:'Estimated based on information provided.'});if(monthly&&food&&payroll)metrics.push({label:'Estimated prime cost',value:`${((food+payroll)/monthly*100).toFixed(1)}%`,note:'Food purchases plus payroll; excludes other operating costs'});if(monthly&&(transactions||customers))metrics.push({label:'Estimated revenue per customer',value:money(monthly/(transactions||customers)),note:transactions?'Based on reported transactions':'Based on reported monthly customer count'});if(monthly&&waste)metrics.push({label:'Estimated waste cost',value:`${(waste/monthly*100).toFixed(1)}%`,note:'Monthly waste ÷ monthly sales'});if(monthly)metrics.push({label:'Revenue per location',value:money(monthly/locations),note:'Monthly estimate'});if(monthly&&employees)metrics.push({label:'Sales per employee',value:money(monthly/employees),note:'Monthly estimate'});if(monthly&&num(a,'thirdPartyPct'))metrics.push({label:'Third-party delivery exposure',value:`${num(a,'thirdPartyPct').toFixed(0)}%`,note:`Approximately ${money(monthly*num(a,'thirdPartyPct')/100)} monthly sales`});if(waste)metrics.push({label:'Annualized food waste',value:`${money(waste*12)} / year`,note:'Estimated based on information provided.'});if((a.restaurantType==='chineseBuffet'||a.restaurantType==='hybrid')&&customers&&food){metrics.push({label:'Estimated food cost per customer',value:money(food/customers),note:'Monthly food purchases ÷ monthly customer count'});if(waste)metrics.push({label:'Estimated waste cost per customer',value:money(waste/customers),note:'Monthly waste ÷ monthly customer count'})}return metrics;
}

export function restaurantRecommendations(a:AssessmentAnswers,s:RestaurantScores):DiagnosticRecommendation[]{
 const monthly=financialValue(a,'monthlySales','monthlySalesRange'),food=financialValue(a,'monthlyFoodPurchases','monthlyFoodRange'),payroll=financialValue(a,'monthlyPayroll','monthlyPayrollRange'),foodPct=monthly&&food?food/monthly*100:num(a,'foodCostPct'),laborPct=monthly&&payroll?payroll/monthly*100:num(a,'laborCostPct'),third=num(a,'thirdPartyPct'),waste=financialValue(a,'monthlyWaste','monthlyWasteRange'),concerns=list(a.ownerConcerns),goals=list(a.ownerGoals);const recs:DiagnosticRecommendation[]=[];
 const add=(r:DiagnosticRecommendation)=>{if(!recs.some(x=>x.title===r.title))recs.push(r)};
 if(foodPct>35||concerns.includes('Food cost too high')||s.health.foodCost<55)add({title:'Establish a food-cost control baseline',priority:foodPct>38?'Critical':'High',impact:'Cost / Profit margin',difficulty:'Moderate',timeline:'0–30 days',reason:`Reported data indicates an estimated ${foodPct?foodPct.toFixed(1)+'%':'unverified'} food cost${monthly&&food?` (${money(food)} of ${money(monthly)} monthly sales)`:''}.`,solution:'Odoo purchasing visibility, vendor price history, recipe or buffet cost controls, and a weekly management dashboard.'});
 if(waste||concerns.includes('Food waste')||s.health.waste<55)add({title:'Measure waste at the source',priority:waste>monthly*.02?'Critical':'High',impact:'Food Cost / Waste',difficulty:'Easy',timeline:'0–30 days',reason:waste?`Reported waste is approximately ${money(waste)} per month, or ${money(waste*12)} annualized.`:'Waste is a stated concern, but no dependable dollar baseline is available.',solution:'Digital waste logging by cause, dish or station, shift, and dollar value; buffet operations should add tray-level tracking.'});
 if(third>25)add({title:'Measure delivery-channel net profitability',priority:'High',impact:'Revenue / Margin',difficulty:'Moderate',timeline:'30–90 days',reason:`Approximately ${third.toFixed(0)}% of sales are reported through third-party delivery, creating material commission and packaging exposure.`,solution:'Integrate delivery revenue, commissions, promotions, refunds, and packaging costs into an owner dashboard; grow direct ordering where viable.'});
 if(s.categories.purchasing<60||concerns.includes('Vendor prices'))add({title:'Create vendor price and purchasing controls',priority:'High',impact:'Cost / Risk',difficulty:'Moderate',timeline:'30–90 days',reason:`Vendor control is currently ${s.categories.purchasing}/100; price history, comparisons, or formal approvals are incomplete.`,solution:'Odoo purchase workflow with approved vendors, invoice capture, historical unit cost, price-change alerts, and approval rules.'});
 if(s.health.inventory<60||concerns.includes('Inventory problems'))add({title:'Replace estimated inventory with repeatable counts',priority:'High',impact:'Cost / Risk',difficulty:'Moderate',timeline:'30–90 days',reason:`Inventory maturity scores ${s.health.inventory}/100, indicating gaps in count frequency, storage visibility, or reorder controls.`,solution:'Ingredient-level inventory, storage locations, minimum levels, reorder points, spoilage and expiration tracking.'});
 if(laborPct>35||concerns.includes('Labor cost too high'))add({title:'Align labor plans with forecast demand',priority:laborPct>40?'Critical':'High',impact:'Labor / Service',difficulty:'Moderate',timeline:'30–90 days',reason:`Estimated labor cost is ${laborPct?laborPct.toFixed(1)+'%':'not yet quantified'}${goals.includes('Reduce labor')?', and labor reduction is a stated owner goal':''}.`,solution:'Sales-by-service-period forecasting, schedule-vs-actual analysis, overtime alerts, and sales-per-labor-hour reporting.'});
 if(s.health.ownerIndependence<60||concerns.includes('Difficulty managing remotely'))add({title:'Reduce dependence on the owner',priority:s.health.ownerIndependence<40?'Critical':'High',impact:'Management / Risk',difficulty:'Moderate',timeline:'30–90 days',reason:`Owner independence is ${s.health.ownerIndependence}/100; routine decisions and employee questions remain concentrated with the owner.`,solution:'Digitize SOPs and recipes, add approval workflows and automated reporting, then deploy a private AI employee knowledge assistant.'});
 if(s.health.technology<65)add({title:'Connect the restaurant management stack',priority:'High',impact:'Management / Labor',difficulty:'Advanced',timeline:'3–6 months',reason:`Technology integration scores ${s.health.technology}/100; management reports multiple systems or repeated data entry.`,solution:'Governed POS, delivery, accounting, purchasing, inventory, payroll, and Odoo integration with one management reporting layer.'});
 if(s.health.aiReadiness>=45&&s.health.inventory>=45&&s.health.foodCost>=45)add({title:'Pilot a private restaurant AI assistant',priority:'Medium',impact:'Labor / Management',difficulty:'Advanced',timeline:'3–6 months',reason:`AI readiness is ${s.health.aiReadiness}/100 and enough operating foundation exists for a controlled pilot.`,solution:'Ground a permission-controlled assistant in approved recipes, SOPs, training, purchasing, and reporting data.'});
 else add({title:'Strengthen operating data before advanced AI',priority:'High',impact:'Management / Risk',difficulty:'Moderate',timeline:'0–30 days',reason:`AI readiness is ${s.health.aiReadiness}/100 and foundational food-cost or inventory controls remain incomplete. Advanced forecasting is not the first priority.`,solution:'First establish dependable sales, purchasing, recipe, inventory, waste, and SOP records. Reassess private AI after those foundations are usable.'});
 if((s.restaurantType==='chineseBuffet'||s.restaurantType==='hybrid')&&(waste||s.health.waste<70))add({title:'Introduce buffet demand and replenishment forecasting',priority:'High',impact:'Food Cost / Waste',difficulty:'Advanced',timeline:'6–12 months',reason:'Buffet production relies on demand timing, tray replenishment, closing-time controls, and high-cost item usage.',solution:'Build customer-count forecasts and preparation recommendations by weekday, service period, station, and item.'});
 return recs.slice(0,8);
}

export function restaurantOpportunityEstimate(a:AssessmentAnswers,s:RestaurantScores):ProfitLeakage{const monthly=financialValue(a,'monthlySales','monthlySalesRange'),food=financialValue(a,'monthlyFoodPurchases','monthlyFoodRange'),payroll=financialValue(a,'monthlyPayroll','monthlyPayrollRange'),waste=financialValue(a,'monthlyWaste','monthlyWasteRange'),hours=num(a,'ownerAdminHours'),annualFood=food*12;const areas:[string,[number,number],string][]=[];if(annualFood)areas.push(['Food cost control',[annualFood*.01,annualFood*.03],`1%: ${money(annualFood*.01)} · 2%: ${money(annualFood*.02)} · 3%: ${money(annualFood*.03)} of estimated annual food purchases.`]);if(waste)areas.push(['Waste reduction',[waste*12*.1,waste*12*.3],`10–30% of ${money(waste*12)} estimated annual waste exposure.`]);if(annualFood&&s.categories.purchasing<70)areas.push(['Purchasing optimization',[annualFood*.005,annualFood*.015],'Conservative 0.5–1.5% range; overlaps food-cost control and is excluded from the total.']);if(payroll&&(num(a,'overtimeCommon')||s.health.labor<60))areas.push(['Labor efficiency',[payroll*12*.005,payroll*12*.015],'Scheduling, overtime, forecasting, and administrative efficiency—not employee reduction.']);if(hours)areas.push(['Management efficiency',[hours*52*20,hours*52*40],'Reported administrative hours valued at $20–$40/hour; not a cash-savings guarantee.']);if(!areas.length&&monthly){const gap=(100-s.overall)/100;areas.push(['Operational improvement',[monthly*12*.005*gap,monthly*12*.02*gap],'Directional range based on sales and readiness gaps; detailed inputs would improve accuracy.'])}const rounded=areas.map(([label,[low,high],basis])=>[label,[Math.round(low/100)*100,Math.round(high/100)*100] as const,basis] as const);const additive=rounded.filter(x=>x[0]!=='Purchasing optimization');return{areas:rounded,total:[additive.reduce((sum,x)=>sum+x[1][0],0),additive.reduce((sum,x)=>sum+x[1][1],0)],disclaimer:'These are preliminary estimates based on information provided and are not guaranteed savings. Some improvement categories may overlap and should not be interpreted as additive without further operational review.'};}

export function restaurantRoadmap(recs:DiagnosticRecommendation[]){return[{phase:'PHASE 1 — VISIBILITY',timeline:'0–30 Days',items:recs.filter(r=>r.timeline==='0–30 days').map(r=>r.title).concat(['Confirm sales, food-cost, labor, and waste baselines']).slice(0,4)},{phase:'PHASE 2 — CONTROL',timeline:'30–90 Days',items:recs.filter(r=>r.timeline==='30–90 days').map(r=>r.title).concat(['Standardize purchasing, inventory, recipes, and SOPs']).slice(0,4)},{phase:'PHASE 3 — AUTOMATION',timeline:'3–6 Months',items:recs.filter(r=>r.timeline==='3–6 months').map(r=>r.title).concat(['Connect POS, ERP, and automated management reporting']).slice(0,4)},{phase:'PHASE 4 — INTELLIGENCE',timeline:'6–12 Months',items:recs.filter(r=>r.timeline==='6–12 months').map(r=>r.title).concat(['Apply forecasting and anomaly detection to governed data']).slice(0,4)}]};

export function restaurantRisks(a:AssessmentAnswers,s:RestaurantScores,recs:DiagnosticRecommendation[]){const risks:string[]=[];const add=(x:string)=>{if(!risks.includes(x))risks.push(x)};const monthly=financialValue(a,'monthlySales','monthlySalesRange'),food=financialValue(a,'monthlyFoodPurchases','monthlyFoodRange'),payroll=financialValue(a,'monthlyPayroll','monthlyPayrollRange');if(monthly&&food/monthly>.35)add(`Food cost estimated at ${(food/monthly*100).toFixed(1)}% of sales`);if(monthly&&payroll/monthly>.35)add(`Labor cost estimated at ${(payroll/monthly*100).toFixed(1)}% of sales`);if(financialValue(a,'monthlyWaste','monthlyWasteRange'))add('Reported food-waste exposure requires source-level measurement');if(s.categories.purchasing<55)add('Vendor prices and purchasing controls lack visibility');if(s.health.inventory<55)add('Inventory shortages, overstocking, or shrinkage may go undetected');if(num(a,'thirdPartyPct')>25)add('Third-party delivery concentration may compress margin');if(s.health.ownerIndependence<60)add('Business continuity depends heavily on the owner');if(s.health.technology<55)add('Disconnected systems weaken management reporting');list(a.ownerConcerns).forEach(x=>add(x));recs.filter(x=>x.priority==='Critical').forEach(x=>add(x.title));return risks.slice(0,5)}

export function consultationSummary(a:AssessmentAnswers,s:RestaurantScores,recs:DiagnosticRecommendation[],opportunity:ReturnType<typeof restaurantOpportunityEstimate>){const metrics=restaurantDerivedMetrics(a);return{businessName:String(a.businessName||''),restaurantType:restaurantTypeLabels[s.restaurantType],cuisine:String(a.cuisineType||'Not provided'),locations:String(a.restaurantLocations||'Not provided'),monthlyRevenue:financialValue(a,'monthlySales','monthlySalesRange')||'Not provided',monthlyFoodPurchases:financialValue(a,'monthlyFoodPurchases','monthlyFoodRange')||'Not provided',monthlyPayroll:financialValue(a,'monthlyPayroll','monthlyPayrollRange')||'Not provided',foodCostPercent:metrics.find(x=>x.label==='Estimated food cost')?.value||String(a.foodCostPct||'Not provided'),laborCostPercent:metrics.find(x=>x.label==='Estimated labor cost')?.value||String(a.laborCostPct||'Not provided'),primeCostPercent:metrics.find(x=>x.label==='Estimated prime cost')?.value||'Not provided',customerCount:financialValue(a,'monthlyCustomerCount','monthlyCustomerRange')||'Not provided',estimatedWaste:financialValue(a,'monthlyWaste','monthlyWasteRange')||'Not provided',pos:String(a.currentPos||'Not provided'),accounting:String(a.accountingSystem||'Not provided'),inventorySystem:String(a.inventorySystem||'Not provided'),topPainPoints:list(a.ownerConcerns).slice(0,5),topGoals:list(a.ownerGoals).slice(0,5),topRisks:restaurantRisks(a,s,recs),topRecommendations:recs.slice(0,5).map(x=>x.title),profitLeakageEstimate:{low:opportunity.total[0],high:opportunity.total[1],areas:opportunity.areas.map(x=>({area:x[0],low:x[1][0],high:x[1][1],basis:x[2]}))},aiReadiness:s.ai,erpReadiness:s.erp,ownerDependency:100-s.health.ownerIndependence,recommendedFirstProject:recs[0]?.title||'Operational baseline review'};}
