export const memberTables = [
  'member_profiles',
  'assessment_reports',
  'opportunity_reports',
  'roi_calculations',
  'member_roadmaps',
  'saved_resources',
  'member_events',
  'admin_staff',
  'member_admin_records',
  'admin_notes',
  'admin_audit_log',
  'consultation_requests',
  'seo_keywords',
  'seo_google_rankings',
  'seo_gsc_metrics',
  'seo_indexing_status',
  'seo_geo_tests',
  'seo_backlinks',
  'seo_authority_profiles',
  'seo_manual_tasks',
] as const;
