import type { Metadata } from 'next';
import { ArrowUpRight } from 'lucide-react';
import { IndustryStories, type IndustryStory } from '@/components/industry-stories';

export const metadata: Metadata = { title: 'Industries', description: 'See how Nexavoris combines AI, ERP, and workflow automation for distribution, field service, construction, retail, manufacturing, and service companies.' };

const stories: IndustryStory[] = [
  { industry: 'Wholesale & Distribution', industrySubtitle: 'Inventory, purchasing, fulfillment, and margin control', image: { src: '/industries/wholesale-distribution.webp', alt: 'Warehouse manager coordinating inventory and fulfillment' }, storytellerRole: 'Warehouse Manager', companyType: 'Regional Wholesale Distributor', shortQuote: 'We stopped chasing three versions of inventory and gave the warehouse and sales team one reliable answer.', fullStory: [
    'Before Nexavoris, our sales team quoted from one spreadsheet while purchasing and the warehouse worked from two others. A stock question could turn into three phone calls, and the answer still depended on who had updated their file last. Returns and damaged shipments were even harder because the process lived mostly in people’s heads.',
    'Now orders, inventory, purchasing, and fulfillment move through one ERP workflow. The private AI assistant helps the team find receiving procedures, customer-specific terms, and return instructions without interrupting a supervisor. Sales can see what is available, purchasing sees what is coming, and the warehouse has a clear queue for the day. We still make the decisions, but the system gives everyone the same current information. That has made handoffs calmer and helped us spot replenishment issues before they become customer problems.'
  ], solutionsUsed: ['Odoo ERP', 'Inventory & Purchasing', 'Private AI Knowledge', 'Workflow Automation'], cta: '/contact?service=wholesale-distribution' },
  { industry: 'HVAC & Field Service', industrySubtitle: 'Dispatch, equipment history, parts, and service follow-up', image: { src: '/industries/hvac-field-service.webp', alt: 'HVAC field technician servicing commercial equipment' }, storytellerRole: 'Service Manager', companyType: 'Regional HVAC Contractor', shortQuote: 'Technicians arrive with the service history and next steps instead of calling the office for every answer.', fullStory: [
    'Our technicians were good at the work, but too much of their day was spent calling the office. Equipment history was in one system, membership details were somewhere else, and the right troubleshooting notes might be in a binder or with a senior technician. Dispatch could assign the job, but it could not give the field team the full picture.',
    'Nexavoris connected CRM, scheduling, work orders, equipment records, parts, and invoicing in Odoo. We also built a private AI assistant around our service manuals and internal procedures. A technician can review the customer history and find the approved process from the job site, while dispatch sees progress without another call. Newer technicians get useful guidance without pretending the AI replaces experience. The biggest change is flow: fewer interruptions, cleaner handoffs, and a service record that is ready when the customer calls again.'
  ], solutionsUsed: ['Field Service ERP', 'CRM & Memberships', 'Private AI Assistant', 'Mobile Workflows'], cta: '/contact?service=hvac-field-service' },
  { industry: 'Construction', industrySubtitle: 'Projects, purchasing, documents, and job-cost visibility', image: { src: '/industries/construction.webp', alt: 'Construction superintendent reviewing work at an active project' }, storytellerRole: 'Project Manager', companyType: 'Commercial General Contractor', shortQuote: 'The current change order, commitment, and field document are finally visible without digging through email chains.', fullStory: [
    'On a busy project, the information was never truly missing—it was just hard to find. Change orders sat in email, commitments lived in accounting, field documents were in shared folders, and job-cost reports arrived after the conversation had already moved on. I spent too much time assembling a picture of the project before I could manage it.',
    'We worked with Nexavoris to connect project tracking, purchasing, document control, and cost visibility in one operating workflow. The AI layer searches our approved project documents and procedures, so the team can locate the right information without relying on a folder expert. It does not approve a change or make a field decision; it gets the supporting facts in front of the responsible person faster. Meetings now start from a current view of commitments, open issues, and project activity. We have fewer surprises and much less hunting through disconnected systems.'
  ], solutionsUsed: ['Project ERP', 'Purchasing', 'AI Document Search', 'Management Dashboards'], cta: '/contact?service=construction' },
  { industry: 'Retail', industrySubtitle: 'Products, customers, purchasing, and multi-location stock', image: { src: '/industries/retail.webp', alt: 'Retail manager coordinating merchandise and inventory' }, storytellerRole: 'Owner', companyType: 'Multi-location Specialty Retailer', shortQuote: 'We can see what each store has, what needs reordering, and which customers need a thoughtful follow-up.', fullStory: [
    'As we added locations, the little workarounds multiplied. Point of sale did one job, inventory counts lived in spreadsheets, and customer lists were split between tools. A return at one store could be invisible to another. Ordering depended on someone noticing a shelf or remembering what sold well last season.',
    'Nexavoris brought point of sale, inventory, purchasing, e-commerce, and customer records into a connected Odoo environment. Store teams now share a reliable product and stock view, and managers can see transfers and replenishment needs before placing an order. We also use automation for practical customer follow-up, without turning every interaction into generic marketing. The system gives us consistency across locations while leaving room for staff to use their judgment. I spend less time reconciling reports and more time understanding what customers are actually asking for.'
  ], solutionsUsed: ['Point of Sale', 'Multi-location Inventory', 'Purchasing', 'CRM Automation'], cta: '/contact?service=retail' },
  { industry: 'Manufacturing', industrySubtitle: 'Materials, planning, production, and quality procedures', image: { src: '/industries/manufacturing.webp', alt: 'Production manager monitoring a modern manufacturing line' }, storytellerRole: 'Production Manager', companyType: 'Component Manufacturer', shortQuote: 'The floor works from the right revision, and shortages show up early enough for us to respond.', fullStory: [
    'We had capable people and solid processes, but the information around production was fragile. Schedules changed on whiteboards, material shortages appeared late, and a revised work instruction did not always reach every station. Training someone new meant pairing them with the one person who knew where everything was kept.',
    'With Nexavoris, manufacturing orders, bills of materials, inventory, purchasing, and quality steps share one ERP foundation. The private AI knowledge system is grounded in our approved work instructions and quality documents, making the current procedure easier to find without opening access to the public internet. Supervisors retain control over revisions and exceptions. The floor now has a clearer production sequence, purchasing can see material pressure sooner, and operators spend less time searching for guidance. It is not flashy; it is simply a more dependable way to keep the plan, materials, and instructions aligned.'
  ], solutionsUsed: ['Manufacturing ERP', 'Materials Planning', 'Quality Workflows', 'Private AI Knowledge'], cta: '/contact?service=manufacturing' },
  { industry: 'Service Companies', industrySubtitle: 'Leads, projects, resources, time, and recurring billing', image: { src: '/industries/service-companies.webp', alt: 'Professional services team coordinating client work' }, storytellerRole: 'Operations Director', companyType: 'Professional Services Firm', shortQuote: 'A signed engagement now becomes scheduled work, tracked time, and accurate billing without repeated data entry.', fullStory: [
    'Our client experience looked polished from the outside, but behind it the team was copying information between sales, project, time-tracking, and billing tools. Project status depended on a weekly meeting, and recurring work was easy to schedule but harder to verify. When a new employee joined, finding the right template or delivery standard took longer than it should.',
    'Nexavoris connected CRM, projects, resource planning, timesheets, and billing so an accepted engagement can move into delivery without being rebuilt. Automations handle routine handoffs and reminders, while a private AI assistant helps staff find approved templates and internal knowledge. We can see project health and unbilled work during the week, not after month-end. The team still owns every client decision and communication; the technology removes the repetition around it. Onboarding is easier, billing is clearer, and operations no longer has to be the human bridge between every system.'
  ], solutionsUsed: ['CRM', 'Project & Resource Planning', 'Timesheets & Billing', 'Private AI Knowledge'], cta: '/contact?service=service-company' }
];

export default function IndustriesPage() { return <main className="industries-page">
  <section className="industries-hero section-shell"><span className="eyebrow">INDUSTRIES / CLIENT STORIES</span><h1>How Nexavoris Works in Your Industry</h1><p>Every business operates differently. See how Nexavoris combines AI, ERP and workflow automation around the way your industry actually works.</p></section>
  <IndustryStories stories={stories}/>
  <section className="section-shell industries-cta"><div><span className="section-index">YOUR OPERATION</span><h2>Your workflow will be different. That is where the conversation starts.</h2></div><a className="button primary" href="/contact?service=industry-workflow">Talk to Nexavoris <ArrowUpRight size={16}/></a></section>
</main>; }
