import {AuthorityPage} from '@/components/authority-page';import {authorityMetadata} from '@/lib/seo';
export const metadata=authorityMetadata('How Nexavoris Works','A practical, phased process for evaluating and implementing private AI, Odoo ERP, and business automation.','/how-nexavoris-works');
export default function Page(){return <AuthorityPage eyebrow="HOW NEXAVORIS WORKS" title="A disciplined path from operational friction to a working system." intro="Every engagement begins with the business process—not a predetermined software package. Scope, timing, and sequence depend on complexity, data quality, risk, and the people responsible for the work." sections={[
{title:'Discovery',body:'We discuss the business outcome, current systems, recurring friction, decision owners, and practical constraints. This is an initial suitability discussion, not a promise of a complete consulting engagement.',items:['Current systems and workflows','Priority outcomes','Known constraints and risks']},
{title:'Process and data review',body:'We map the selected workflow, inputs, exceptions, approvals, records, and handoffs. We assess whether the data is reliable enough to support ERP, automation, or AI.',items:['Process owners and exceptions','Data quality and permissions','Integration dependencies']},
{title:'Roadmap and pilot',body:'Recommendations are sequenced into a practical roadmap. Where uncertainty is material, a limited pilot tests assumptions before broader implementation.',items:['Defined scope and acceptance criteria','Human review and fallback','Measurable operating baseline']},
{title:'Implementation and training',body:'Configuration, migration, integration, testing, documentation, and training are managed as one operating change. Technology is not complete merely because it runs.',items:['User acceptance testing','Role-based training','Documented ownership']},
{title:'Ongoing improvement',body:'After launch, the system is monitored and refined as employees use it and the business changes. New capability is introduced only when the foundation is ready.',items:['Support and monitoring','Measured improvement','Phased expansion']},
]} />}
