import type { Metadata } from 'next';
import { ArrowRight, BrainCircuit, Boxes, Check, LifeBuoy } from 'lucide-react';

export const metadata: Metadata = { title: 'Pricing', description: 'Planning-level pricing for private enterprise AI, ERP implementation, and ongoing Nexavoris support.' };

const aiPlans = [
  { name:'AI Foundation', price:'$7,500', note:'starting investment', fit:'For small teams centralizing company knowledge', features:['Private knowledge assistant','Up to 2,500 source documents','SOP and policy search','Core user permissions','Administrator training','60-day launch support'] },
  { name:'AI Growth', price:'$15,000', note:'typical starting point', fit:'For established companies deploying AI across departments', popular:true, features:['Department-level knowledge spaces','Up to 10,000 source documents','Document intelligence workflows','Employee training assistant','Management reporting use cases','ERP integration readiness'] },
  { name:'AI Enterprise', price:'$30,000+', note:'scoped engagement', fit:'For complex, controlled, or dedicated deployments', features:['Dedicated or customer-controlled infrastructure','Advanced permissions and governance','Multiple business units','Custom AI workflows and agents','System and ERP integrations','Security and adoption planning'] },
];
const erpPlans = [
  { name:'ERP Core', price:'$5,000', note:'starting investment', fit:'For one company replacing spreadsheets or disconnected tools', features:['Discovery and process mapping','CRM and sales','Purchasing and inventory','Basic accounting integration','Initial data migration','Core employee training'] },
  { name:'ERP Operations', price:'$11,250', note:'typical starting point', fit:'For growing companies connecting multiple workflows', popular:true, features:['Everything in ERP Core','Field service or project management','Dashboards and reporting','Workflow approvals and automation','Third-party integrations','Expanded migration and training'] },
  { name:'ERP Enterprise', price:'$21,250+', note:'scoped engagement', fit:'For multi-company, complex, or highly customized operations', features:['Multi-company architecture','Custom modules and integrations','Advanced operational workflows','Complex data migration','Phased department rollout','Change management and governance'] },
];
const carePlans = [
  { name:'Essential Care', price:'$300', note:'per month', fit:'Reliable support for stable systems', features:['Up to 5 support hours','System monitoring','Monthly maintenance review','Email support','Quarterly improvement review'] },
  { name:'Managed Operations', price:'$800', note:'per month', fit:'Ongoing optimization for active teams', popular:true, features:['Up to 12 support hours','Priority issue handling','Monthly optimization work','User and workflow assistance','Monthly operating review'] },
  { name:'Priority Partnership', price:'$1,500', note:'per month', fit:'Continuous improvement for mission-critical systems', features:['Dedicated monthly capacity','Priority response','AI and ERP optimization','New workflow development','Executive roadmap reviews'] },
];

type Plan = {name:string;price:string;note:string;fit:string;features:string[];popular?:boolean};
function PlanGroup({icon:Icon,label,title,intro,plans}:{icon:typeof BrainCircuit;label:string;title:string;intro:string;plans:Plan[]}){return <section className="pricing-group section-shell"><div className="pricing-heading"><div className="pricing-icon"><Icon size={22}/></div><div><span className="section-index">{label}</span><h2>{title}</h2><p>{intro}</p></div></div><div className="pricing-grid">{plans.map(plan=><article key={plan.name} className={plan.popular?'popular':''}>{plan.popular&&<div className="popular-label">MOST COMMON</div>}<h3>{plan.name}</h3><div className="price">{plan.price}</div><span className="price-note">{plan.note}</span><p>{plan.fit}</p><ul>{plan.features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul><a href="/contact">Discuss this package <ArrowRight size={16}/></a></article>)}</div></section>}

export default function PricingPage(){return <main><section className="pricing-hero section-shell"><span className="section-index">PRICING</span><h1>Practical investment levels for serious business systems.</h1><p>These planning-level packages help you understand the likely investment before discovery. Your final proposal is based on users, data, workflows, integrations, infrastructure, and rollout requirements.</p><a className="button primary" href="/contact">Request a scoped estimate <ArrowRight size={17}/></a></section><PlanGroup icon={BrainCircuit} label="PRIVATE ENTERPRISE AI" title="Company AI implementation" intro="Secure AI systems grounded in your company knowledge, procedures, products, and documents." plans={aiPlans}/><PlanGroup icon={Boxes} label="ERP IMPLEMENTATION" title="Company ERP setup" intro="Business process design, configuration, migration, integration, training, and launch support." plans={erpPlans}/><PlanGroup icon={LifeBuoy} label="ONGOING SUPPORT" title="Monthly maintenance and improvement" intro="Predictable access to the team that understands your systems, workflows, and roadmap." plans={carePlans}/><section className="pricing-notes section-shell"><h2>What affects final pricing?</h2><div>{['Number of users and business entities','Data quality and migration volume','Custom workflows and approval rules','Third-party software integrations','Infrastructure and security requirements','Training, rollout, and change management'].map(x=><span key={x}><Check size={14}/>{x}</span>)}</div><p>Software licenses, dedicated hardware, cloud consumption, third-party subscriptions, travel, and extensive data remediation are quoted separately when required. Prices shown are planning estimates in USD and do not constitute a binding proposal.</p></section><section className="mini-cta section-shell"><div><span className="section-index">GET A REAL NUMBER</span><h2>Start with a focused discovery conversation.</h2></div><a className="button primary" href="/contact">Schedule a Consultation <ArrowRight size={17}/></a></section></main>}
