import type { Metadata } from 'next'; import Image from 'next/image'; import { SolutionPage } from '@/components/solution-page'; import { ArrowRight, BrainCircuit, Check, Database, ShieldCheck, Workflow } from 'lucide-react';
export const metadata:Metadata={title:'AI + ERP Integration',description:'Connect private AI to live ERP data and controlled business workflows.'};
const items=[['Ask operational questions','Turn live sales, customer, inventory, delivery, and purchasing data into immediate, understandable answers.'],['Create business records','Draft quotations, prepare purchase recommendations, or assemble work orders through a governed AI workflow.'],['Find what needs attention','Identify dormant customers, low stock, delivery risks, and process exceptions before they become larger problems.'],['Automate across departments','Coordinate actions between CRM, sales, inventory, purchasing, accounting, and operations without duplicating work.'],['Protect control and accountability','Design permissions, approvals, source grounding, and auditability into every assisted action.'],['Improve continuously','Use real business outcomes to refine workflows, knowledge, and employee experience over time.']];
const images=[{src:'/ai-erp/operational-questions.webp',alt:'Business leader asking a question about current operational data'},{src:'/ai-erp/create-records.webp',alt:'Employee preparing governed business records for approval'},{src:'/ai-erp/find-attention.webp',alt:'Operations manager identifying exceptions across customers, stock, and deliveries'},{src:'/ai-erp/cross-department-automation.webp',alt:'Connected workflow coordinating multiple business departments'},{src:'/ai-erp/control-accountability.webp',alt:'Controlled workflow with permissions, approval, references, and audit records'},{src:'/ai-erp/continuous-improvement.webp',alt:'Team refining an operational workflow using measured outcomes'}];
const flow=[['01','Understand the request','The employee asks in everyday language. The system identifies the business intent, relevant records, and permitted scope.'],['02','Ground the answer','Private company knowledge and current ERP data are retrieved so the response reflects real policies, customers, products, and transactions.'],['03','Prepare the action','AI drafts the recommendation, document, or record change while preserving source details and business rules.'],['04','Review and execute','The right employee approves sensitive actions. The ERP records the result, ownership, and next step for a complete audit trail.']];
const examples=[['Sales','Summarize an account, identify inactive customers, draft follow-up messages, and prepare quotations using current pricing and availability.'],['Purchasing','Review demand, lead times, and low-stock risk; then prepare supplier recommendations for an authorized buyer.'],['Operations','Surface late orders, service bottlenecks, capacity constraints, and exceptions that need a manager’s attention.'],['Customer service','Bring together order history, policies, product information, and open issues so employees can respond accurately and consistently.'],['Finance','Explain operational drivers behind receivables, margins, and cash-flow changes without replacing financial review or approval.'],['Management','Turn live operating data into concise daily briefings, trend summaries, and prioritized decisions.']];
export default function Page(){return <SolutionPage eyebrow="AI + ERP" title="Intelligence connected to the work itself." intro="A standalone AI can answer questions. An AI connected to ERP can understand current operations, surface the next best action, and—within your rules—help move work forward." quote="Which customers have not ordered in 60 days, and prepare a follow-up list for the sales team?" items={items.map(([title,body],i)=>({title,body,image:images[i]}))}>
  <section className="ai-erp-explainer">
    <div className="section-shell ai-erp-intro"><div><span className="section-index">HOW THE CONNECTION WORKS</span><h2>One governed path from question to action.</h2></div><p>ERP supplies the operational truth. Your private knowledge supplies the context. AI makes both easier to understand and use—without giving an unrestricted assistant control of the business.</p></div>
    <div className="section-shell ai-erp-section-visual dark"><Image src="/ai-erp/connection-works.webp" alt="Operations leader and technology specialist reviewing connected business information" fill sizes="(max-width: 700px) 100vw, 1200px"/></div>
    <div className="section-shell ai-erp-pillars"><article><Database/><h3>Live operational data</h3><p>Customers, products, inventory, orders, purchasing, projects, service activity, and financial status.</p></article><article><BrainCircuit/><h3>Company knowledge</h3><p>Policies, procedures, product guidance, contracts, training material, and the expertise your team relies on.</p></article><article><ShieldCheck/><h3>Controlled execution</h3><p>Role-based permissions, approval thresholds, source references, action logs, and human review where risk requires it.</p></article></div>
  </section>
  <section className="section-shell ai-erp-flow"><div className="section-head"><span className="section-index">A PRACTICAL WORKFLOW</span><h2>Useful automation still keeps people accountable.</h2><p>The system separates understanding, evidence, preparation, and execution so employees can move faster without losing oversight.</p></div><div className="ai-erp-section-visual"><Image src="/ai-erp/practical-workflow.webp" alt="Employee and manager reviewing a prepared business action before approval" fill sizes="(max-width: 700px) 100vw, 1200px"/></div><div>{flow.map(([number,title,body])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="ai-erp-examples"><div className="section-shell"><div className="section-head"><span className="section-index">WHERE IT CREATES VALUE</span><h2>One connected assistant across the operation.</h2><p>The same governed foundation can support different departments while respecting the data and actions each role is allowed to use.</p></div><div className="ai-erp-section-visual"><Image src="/ai-erp/creates-value.webp" alt="Cross-functional team using connected information during an operations review" fill sizes="(max-width: 700px) 100vw, 1200px"/></div><div className="ai-erp-example-grid">{examples.map(([title,body])=><article key={title}><Workflow/><h3>{title}</h3><p>{body}</p></article>)}</div><a className="text-link" href="/contact?service=ai-erp">Discuss your highest-value workflow <ArrowRight size={16}/></a></div></section>
  <section className="section-shell ai-erp-guardrails"><div><span className="section-index">DESIGNED FOR TRUST</span><h2>Automation should be powerful, observable, and reversible.</h2></div><ul>{['Responses grounded in approved company sources','Least-privilege access based on each employee’s role','Human approval before sensitive or high-impact actions','Source references and action histories for accountability','Testing, monitoring, and improvement against real outcomes','Clear fallbacks when confidence or required data is insufficient'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></section>
</SolutionPage>}
